### ISSUE TITLE
Nginx 启动失败(最后一步显示)

### ISSUE THREAD

**Issue by zry118** [wulabing/Xray_onekey#170]
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.servic
e" and "journalctl -xe" for details.
[错误]  Nginx 启动 失败

**Comment by YMChenLiye** [comment]
我是因为`/data/v2ray.crt && /data/v2ray.key`不存在,所以nginx启动失败.
你可以观察一下详细信息,是否也是因为这个原因导致的.
执行`.acme.sh/acme.sh --installcert -d domain.yours --fullchainpath /data/v2ray.crt --keypath /data/v2ray.key --ecc --force`拷贝证书到指定路径. (替换自己的域名)
因为acme脚本在root用户执行时需要参数 `--force`

**Comment by zry118** [comment]
重新db9重装后没有问题，使用centos7一直出问题 不是证书问题


发自我的iPhone

**Comment by purezhi** [comment]
同样是这个问题。

**Comment by mattocci27** [comment]
对于debian 9.7、10.2和centos 8，同样的问题。

**Comment by wulabing** [comment]
最近发现有部分相似的问题反馈，我会查一下问题

Masatoshi Katabuchi <notifications@github.com> 于2020年2月17日周一 上午11:12写道：

**Comment by NeriakTo** [comment]
Ubuntu 18.04 在非全新干净系统下（安装过 bbr、bbr2 等并移除过），亦会有 Nginx 启动失败讯息，经查为 masked，后测试重新建一台干净的 Ubuntu 18.04 再安装后成功。

**Comment by zry118** [comment]
看起来是的



发自我的iPhone

**Comment by jp-sun** [comment]
@wulabing 我也碰到了这个问题，不过我有一些发现，可能是因为之前签发过证书了，再跑到脚本里的这个命令的时候 $HOME/.acme.sh/acme.sh --issue -d ${domain} --standalone -k ec-256 --force， acme.sh好像移除了/root/.acme.sh/domain_ecc下的domian.key文件，然后就出现了上面的错误。可以删除文件夹/root/.acme.sh/domain_ecc再跑脚本就可以了。

**Comment by wulabing** [comment]
感谢反馈


jp-sun <notifications@github.com> 于2020年2月23日周日 下午4:46写道：

**Comment by liuhuyu** [comment]
Ubuntu 18.04 CentOS 7.3 都试了 都重置了两遍 全新干净系统 server_names_hash_bucket_size改过 和 /data/v2ray.crt && /data/v2ray.key 确认过都在 还是启动失败 ....

**Comment by mattocci27** [comment]
成功使用CentOS8.1了。我什么都没改变。我的网域有问题。

**Comment by buoyont** [comment]
debian 9.8 之前安装过Trojan，卸载后运行安装脚本 ngnix无法启动显示 为   Nginx is masked

**Comment by BlueBetters** [comment]
如题，亲测在 nginx 配置文件里 http 下加上一行 就解决了
`server_names_hash_bucket_size 512;`

**Comment by grant7788** [comment]
全新CentOS 7，一键安装后nginx失败，v2ray正常。
搜全盘未发现nginx相关的文件(配置文件、启动文件都没有)。
请教要如何解决。非常感谢。
