### ISSUE TITLE
能不能搞一个trojan的一键

### ISSUE THREAD

**Issue by darkrain88** [wulabing/Xray_onekey#189]
伸手党, 要求来 了.

谢谢

**Comment by wulabing** [comment]
已经有了，由其他人编写及维护

darkrain88 <notifications@github.com> 于2020年2月25日周二 下午2:13写道：

**Comment by darkrain88** [comment]
求链接, 你写的不错

**Comment by easyinplay** [comment]
非常感谢wulabing朋友的辛苦工作，使用过很多脚本还是觉得这里的最好用。希望可以集成一下trojan，可以同时部署 v2ray ws-tls 和 trojan（防止某一天突然因为不可抗力其中的一张方式不能用了） ，虽然也能找到其他部署trojan的脚步但是找不到可以同时部署的，因为都占用443端口，如果安装两个脚本会提示安装失败，希望朋友能够出一个集成的一键脚本可以同时部署这两种方式

**Comment by ChengEast** [comment]
> 非常感谢wulabing朋友的辛苦工作，使用过很多脚本还是觉得这里的最好用。希望可以集成一下trojan，可以同时部署 v2ray ws-tls 和 trojan（防止某一天突然因为不可抗力其中的一张方式不能用了） ，虽然也能找到其他部署trojan的脚步但是找不到可以同时部署的，因为都占用443端口，如果安装两个脚本会提示安装失败，希望朋友能够出一个集成的一键脚本可以同时部署这两种方式

两个服务占同个端口，你在装的时候就指定或设置不同的端口就好了啊。。。

**Comment by yuanyue456** [comment]
> > 非常感谢wulabing朋友的辛苦工作，使用过很多脚本还是觉得这里的最好用。希望可以集成一下trojan，可以同时部署 v2ray ws-tls 和 trojan（防止某一天突然因为不可抗力其中的一张方式不能用了） ，虽然也能找到其他部署trojan的脚步但是找不到可以同时部署的，因为都占用443端口，如果安装两个脚本会提示安装失败，希望朋友能够出一个集成的一键脚本可以同时部署这两种方式
> 
> 两个服务占同个端口，你在装的时候就指定或设置不同的端口就好了啊。。。

共存可以使用nginx的443分流到v2ray ws-tls 和 trojan，所以這個腳本能增加trojan共存，就是全網第一個一鍵腳本了
