### ISSUE TITLE
全部安装好之后，pc可用ios用不了

### ISSUE THREAD

**Issue by meichuanyi** [wulabing/Xray_onekey#192]
Debian9系统和centos7,8都试过问题相同，选择wesite法，安装好之后，在pc上用Chrome打不开自己的伪装网站，显示拒绝了 网站我们的连接请求。（科学上网没有出现问题）
但是在ios上使用小火箭连接就出现链接不安全，无法连接

**Comment by Harley-K** [comment]
请问解决了么
