### ISSUE TITLE
请问给域名DNS添加IPv6地址后能走IPv6的流量吗

### ISSUE THREAD

**Issue by tangbanxianing** [wulabing/Xray_onekey#195]
校园网用户只想用IPv6

**Comment by cchhuuaann1** [comment]
> 校园网用户只想用IPv6

参考这个issue 修改/etc/nginx/conf/conf.d/v2ray.conf 让Nginx监听ipv6 然后重启Nginx服务 在客户端上把服务器地址填成你的ipv6地址即可
https://github.com/wulabing/V2Ray_ws-tls_bash_onekey/issues/83#issuecomment-534632417
