### ISSUE TITLE
软路由op固件 SSR Plus +添加木马程序无法播放youtube的视频

### ISSUE THREAD

**Issue by nathanxie** [wulabing/Xray_onekey#198]
昨天软路由更新固件，用SSR Plus +添加Trojan节点遇到以下问题，请大佬麻烦帮我看下。
1、连接Trojan节点后，谷歌搜索无法打开
2、油管首页能正常打开，并能正常搜索视频内容，但是点击播放跳转到播放页面就一直无法正常播放，我查看视频速度（详细统计信息），显示没有速度
3、我通过SSR Plus +设置全局模式进行网页测速和fast测试的时候，均能跑满我的300m宽带，测试ip也都是我vps的ip
4、我用了3个种模式，gfw和绕过大陆，还有全局模式。只有全局模式能正常测速，以上1，2点还是存在

**Comment by cchhuuaann1** [comment]
trojan ? 我这里是v2ray 你来错地方了
