### ISSUE TITLE
能否考虑加一个PHP的支持？

### ISSUE THREAD

**Issue by zcrv5** [wulabing/Xray_onekey#201]
现在HTML的源码都没多少好的了，而PHP则是各种各样的源码茫茫多，而且效果也非常不错，我自己尝试装了个PHP然后看了好多教程然而依然没办法调用，所以请问作者可否做一个带PHP的版本，甚至是MYSQL的版本，这样甚至能直接做一个可以用的网站了。

**Comment by puzzle9** [comment]
脚本是提供方便的
当然 自己安装也没什么问题
不过 既然入了这个坑 还是渔好一点
不是吗
