### ISSUE TITLE
用了几天这个脚本，谷歌云300美金费用在几天内用光

### ISSUE THREAD

**Issue by zry118** [wulabing/Xray_onekey#205]
谷歌云自己没怎么用 没分享 ，但是今天被谷歌工单警告，超标流量

**Comment by zry118** [comment]
概要
My First Project (id: cohesive-point-250202) 似乎正在进行拒绝服务 (DoS) 攻击。这违反了 Google Cloud Platform 服务条款或使用限制政策（包括您可能正在使用的 Google API 的服务条款）。

 

详细信息
受影响的项目/VM：My First Project (id: cohesive-point-250202)/instance-5:asia-east2-b

说明：源自 VM instance-5:asia-east2-b 的异常出站活动导致我们针对受影响的资源设置了出站带宽速率限制。

时间范围：从 2020-03-03 16:01 到 2020-03-03 16:05（美国太平洋时间）

 
后续步骤
要解决此问题，请尽快停止相关实例，确保您的出站流量符合预期，并核实您的项目是否遭到了入侵。

**Comment by zry118** [comment]
2020年3月1日至31日 | Credit FreeTrial:Credit-014B7D-2F0411-F87D33 | −US$205.48
2020年3月1日至31日 | Credit External IPs will not be charged until April 1, 2020. | −US$0.39
2020年3月1日至31日 | Compute Engine Storage PD Capacity in Hong Kong: 0.94 GB*月 | US$0.05
2020年3月1日至31日 | Compute Engine Static Ip Charge: 68.505 小时 | US$0.68
2020年3月1日至31日 | Compute Engine Network Internet Egress from Hong Kong to China: 2673.268 GB |

**Comment by zry118** [comment]
2020年3月1日至31日 | Compute Engine Network Internet Egress from Hong Kong to APAC: 3.46 GB | US$0.42
-- | -- | --
2020年3月1日至31日 | Compute Engine Micro Instance with burstable CPU running in Hong Kong: 60.411 小时 | US$0.64
2020年3月1日至31日 | Compute Engine Micro Instance with burstable CPU running in APAC: 36.682 小时 | US$0.33
2020年3月1日至31日 | Compute Engine External IP Charge on a Standard VM: 97.087 小时 | US$0.39
2020年3月3日 | 已安排自动付款：从支票帐号  • • • • 5126支付 US$300.00 | US$0.0

总共就运行60 多个小时

**Comment by cchhuuaann1** [comment]
请自行检查你的服务器是不是因为弱口令被爆破

**Comment by xinwf** [comment]
我也不知道是不是用这个脚本的原因，我是用的pacificrack，刚搭好第三天晚上服务器被挂起，说滥用，经过3天后，给我解封了，流量异常，大的可怕，不知道在干嘛，上线一小时，10G流量没有了，都没有人连，我直接重装系统了，如果再这样下去，估计还是要被官方挂起。这个用了nginx做伪装，在实际部署完成的VPS上有个.acme文件夹，下面有很多脚本，我感觉是不是有问题，如果只是部署一个3D化学元素周期表哪需要这么多脚本，还在慢慢查，而且这里面有个qiniu.sh，打开qiniu.com，发现这是个做数据挖掘的网站，但是没查到在哪里调用了这个脚本，刚把服务器上的root文件夹down下来，慢慢查

**Comment by xinwf** [comment]
站主说的有道理，也有可能是弱口令被爆，我的root密码确实太简单了，debian系统，密码就叫debian，这是今早登录几次记录的信息
![ipinfo](https://user-images.githubusercontent.com/41889613/80268136-95f25a00-86d7-11ea-8b76-158bca61a8a2.png)
![ipinfo2](https://user-images.githubusercontent.com/41889613/80268184-c20ddb00-86d7-11ea-91a7-ce9382d54187.png)
![ipinfo3](https://user-images.githubusercontent.com/41889613/80268185-c803bc00-86d7-11ea-94c2-18d5dd71b12a.png)

**Comment by cchhuuaann1** [comment]
> 我也不知道是不是用这个脚本的原因，我是用的pacificrack，刚搭好第三天晚上服务器被挂起，说滥用，经过3天后，给我解封了，流量异常，大的可怕，不知道在干嘛，上线一小时，10G流量没有了，都没有人连，我直接重装系统了，如果再这样下去，估计还是要被官方挂起。这个用了nginx做伪装，在实际部署完成的VPS上有个.acme文件夹，下面有很多脚本，我感觉是不是有问题，如果只是部署一个3D化学元素周期表哪需要这么多脚本，还在慢慢查，而且这里面有个qiniu.sh，打开qiniu.com，发现这是个做数据挖掘的网站，但是没查到在哪里调用了这个脚本，刚把服务器上的root文件夹down下来，慢慢查

可否将qiniu.sh这个脚本发送到 holtom.rintaro4054@gmail.com

**Comment by xinwf** [comment]
> > 我也不知道是不是用这个脚本的原因，我是用的pacificrack，刚搭好第三天晚上服务器被挂起，说滥用，经过3天后，给我解封了，流量异常，大的可怕，不知道在干嘛，上线一小时，10G流量没有了，都没有人连，我直接重装系统了，如果再这样下去，估计还是要被官方挂起。这个用了nginx做伪装，在实际部署完成的VPS上有个.acme文件夹，下面有很多脚本，我感觉是不是有问题，如果只是部署一个3D化学元素周期表哪需要这么多脚本，还在慢慢查，而且这里面有个qiniu.sh，打开qiniu.com，发现这是个做数据挖掘的网站，但是没查到在哪里调用了这个脚本，刚把服务器上的root文件夹down下来，慢慢查
> 
> 可否将qiniu.sh这个脚本发送到 [holtom.rintaro4054@gmail.com](mailto:holtom.rintaro4054@gmail.com)

好的

**Comment by xinwf** [comment]
脚本是无辜的，重做系统后，重新用该脚本搭建翻墙，4个小时了，未见异常流量，不知道之前从哪复制的脚本出问题了，或者真的是密码太简单被入侵了，现在已经正常了，几个加速的也测了，目前感觉bbrplus是比较理想的

**Comment by zazitufu** [comment]
建议所有准备长期使用的服务器都用密钥登陆。。。GCP配置密钥很方便的
