### ISSUE TITLE
这个脚本能在LXC虚拟化的VPS中用吗

### ISSUE THREAD

**Issue by SomeoneCalledMing** [wulabing/Xray_onekey#208]
这个脚本能在LXC虚拟化的VPS中用吗

**Comment by LiJinChang** [comment]
好像不行，前几天撸的免费德国小鸡安装不了。
![2020-03-17_161711](https://user-images.githubusercontent.com/1154661/76836005-09988000-686b-11ea-9018-7f110135b8b2.png)
