### ISSUE TITLE
GCP上面搭的WS+TLS+V2RAY的协议都失效！只有手机的网可以用PC端全部无法使用？

### ISSUE THREAD

**Issue by siemenstutorials** [wulabing/Xray_onekey#212]
这几天为什么所有的GCP上面搭的WS+TLS+V2RAY的协议都失效！只有手机的移动网可以用PC端WIFI这种模式的节点全部无法使用？

**Comment by Ridup** [comment]
+1  手机可以使用 但电脑不可以 检查了版本和配置 都没问题呀

**Comment by cchhuuaann1** [comment]
> 这几天为什么所有的GCP上面搭的WS+TLS+V2RAY的协议都失效！只有手机的移动网可以用PC端WIFI这种模式的节点全部无法使用？

GCP是给联通用户玩的 移动电信就别想了
