### ISSUE TITLE
搭建成功用的google云网络非常慢！

### ISSUE THREAD

**Issue by Havynlam** [wulabing/Xray_onekey#214]
本地是千M电信光纤，服务器选用日本的，搭建后网速非常慢，打开youtube 测试速度 不到300kbps
求大神支招是什么原因?????

**Comment by Havynlam** [comment]
数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 69ms，最长 = 70ms，平均 = 69ms

这是ping 至日本服务器的

**Comment by Havynlam** [comment]
现在市面上的收费v2ray 感觉速度蛮快的，为啥自己搭的差这么远？？？

**Comment by sacrish** [comment]
这是电信的问题，加大力度QoS限速，持续一两个月了。尤其往日本，已经堵死。速度快的飞机场可能是买了CN2之类线路好一点的机房，愿意加钱的话你也可以的。

**Comment by jzh33** [comment]
从前天晚上开始，我也挂了，断流+连接不上，300m联通，换个ip新建一个能顶一会，然后就又不行了，感觉是被gfw识别之后干扰了。

**Comment by cchhuuaann1** [comment]
> 本地是千M电信光纤，服务器选用日本的，搭建后网速非常慢，打开youtube 测试速度 不到300kbps
> 求大神支招是什么原因?????

加钱上CN2 GIA 电信不走CN2 GIA没法用 GCP是给联通用户玩的 移动电信就别想了

**Comment by JamesMarts** [comment]
> 现在市面上的收费v2ray 感觉速度蛮快的，为啥自己搭的差这么远？？？
兄弟 请问你一般在哪买收费的机场

**Comment by JamesMarts** [comment]
兄弟 请问你一般在哪买收费的机场

**Comment by hy817120** [comment]
最近几月真的是慢的。。。。。。。。

**Comment by yigeni** [comment]
> 兄弟 请问你一般在哪买收费的机场

高端机场节点，有iplc不过墙专线有bgp中转专线有性价比高的等等，不断线不断流，无敏感时期…
https://t.me/yigeni_group/76
