### ISSUE TITLE
v2ray+ws+tls+ngnix 已经被ban

### ISSUE THREAD

**Issue by jzh33** [wulabing/Xray_onekey#216]
v2ray+ws+tls+ngnix+cdn已经被ban了，各位同学有遇到问题的吗？我想了解一下是我个例还是大家都是。

**Comment by chenjihong99** [comment]
能看下你客户端的配置吗

**Comment by liu191388548** [comment]
可以使用 目前没有吧

**Comment by jzh33** [comment]
我确认是被ban了，aws，gcp都废了。我现在正在想办法拯救我的服务器呢，也不是不通，而是被干扰，油管没速度，网页转圈圈。

**Comment by chenjihong99** [comment]
> 我确认是被ban了，aws，gcp都废了。我现在正在想办法拯救我的服务器呢，也不是不通，而是被干扰，油管没速度，网页转圈圈。

你检查过你的线路吗

**Comment by jzh33** [comment]
内网一切正常，不管是不是走cdn都是一样，我感觉就是流量被识别然后被干扰。我试过非443端口，十多分钟后就直接不通了，连接错误。套不套cdn一样结果，所以我认为是GFW识别了v2ray的流量直接干扰了。

**Comment by cchhuuaann1** [comment]
> v2ray+ws+tls+ngnix+cdn已经被ban了，各位同学有遇到问题的吗？我想了解一下是我个例还是大家都是。

你是个例

**Comment by blackforest1840** [comment]
> 内网一切正常，不管是不是走cdn都是一样，我感觉就是流量被识别然后被干扰。我试过非443端口，十多分钟后就直接不通了，连接错误。套不套cdn一样结果，所以我认为是GFW识别了v2ray的流量直接干扰了。

解决方法：1、关闭系统中 alibabaprotect和qqprotect进程2、下载火绒监控访问软件文件夹的进程，自己编个规则即可3、每次启动前检查第一项。
这两个进程会访问软件文件夹并且追踪你的流量。本人亲测

**Comment by cchhuuaann1** [comment]
> 内网一切正常，不管是不是走cdn都是一样，我感觉就是流量被识别然后被干扰。我试过非443端口，十多分钟后就直接不通了，连接错误。套不套cdn一样结果，所以我认为是GFW识别了v2ray的流量直接干扰了。

谁要是敢说他能识别Nginx反代的v2ray 那2020年的科技进步奖就是他的了 别一天天光在那里嘴上说识别 拿出点实际的干货 论文/学术报告都行

**Comment by sd19836311** [comment]
你应该是个例吧。目前我服务器运行稳定了有一个星期了。没有被gg。

**Comment by jiangdashao** [comment]
自己使用不当造成的吧，反正我开了七八个机子，从来没被ban过

**Comment by MaverickTse** [comment]
如果Network內有Cisco Umbrella/Fortigate 一類東西, 的確Server用幾小時後就可能被Ban (連SSH也連不上)

**Comment by disuwww** [comment]
我这边也有这种情况，间断 ，域名无法解析  ，网站无法访问
