### ISSUE TITLE
Failed to copy V2Ray binary and resources

### ISSUE THREAD

**Issue by SmRiley** [wulabing/Xray_onekey#219]
![image](https://user-images.githubusercontent.com/45205313/77392231-6a790880-6dd5-11ea-9969-f52f18012fa2.png)

**Comment by hxy493045049** [comment]
+1  刚好碰到同一个问题

**Comment by hxy493045049** [comment]
我把vps换成了centOs7就没这问题了

**Comment by Hsiao-Jan** [comment]
+1 debian系统

**Comment by cchhuuaann1** [comment]
脚本用了官方的v2ray链接 install.direct/go.sh 前几天出现的问题 好像是v2ray的锅 不是脚本的问题 有能力的话手动改一下脚本换成其他的v2ray下载链接

**Comment by dao3300** [comment]
CentOS 升级一下就过了这关，yum -y update。

**Comment by Filterrr** [comment]
手动更新v2ray嘛，在官网下载个包复制替换进这个目录/usr/bin/v2ray，在重启就能解决
