### ISSUE TITLE
另一条道路支持多用户——V2Ray变身Shadowsocks服务器

### ISSUE THREAD

**Issue by charleslxa** [wulabing/Xray_onekey#221]
之前一直想V2Ray支持多用户，结果查了很多资料，配置了N种方案，无效.......于是看到了另外一条思路。

修改 vi /etc/v2ray/config.json 文件，现在需要在配置文件中增加对shadowsocks协议的支持。需要在配置文件中增加如下内容：

 "inbounds": [ 
   ........................
                           ]
这里开始增加对shadowsocks协议的支持，支持多用户
，  //逗号  
"inboundDetour": [
{
    "protocol": "shadowsocks", // 开启 Shadowsocks
    "port": 30001, // 监听 30001 端口
    "settings": {
    "method": "aes-256-cfb", // 加密方式，支持 aes-256-cfb 和 aes-128-cfb
    "password": "v2ray", // 密码，必须和客户端相同
    "udp": false // 是否开启 UDP 转发
  }
  },
  {
    "protocol": "shadowsocks", // 开启 Shadowsocks
    "port": 30002, // 监听 30002 端口，由于 Shadowsocks 的限制，多用户的时候只能开多个端口
    "settings": { // 配置和上述类似
    "method": "aes-256-cfb",
    "password": "v2ray-2",
    "udp": false
  }
} 
],

举一个例子：
     "inbounds": [
   ...................
               ]
,
"inboundDetour": [
{
    "protocol": "shadowsocks",
    "port": 30001,
    "settings": {
    "method": "aes-256-gcm",
    "password": "v2ray",
    "udp": false
  }
}
],
systemctl restart  v2ray.service
注意检查防火墙是否开放端口
 然后重启v2ray，用影棱客户端连接到上面定义的30001和30002端口进行测试了。正常情况下会连接成功，shadowsocks服务器替换支持多用户。 

最后还有一点，博主脚本/etc/v2ray/config.json文件里面的 "inbounds":里面的端口好像根本不起作用，默认情况下是443端口，但是config.json文件里面的端口不是443，这种情况怎么解释？

**Comment by wangfeng35** [comment]
> 最后还有一点，博主脚本/etc/v2ray/config.json文件里面的 "inbounds":里面的端口好像根本不起作用，默认情况下是443端口，但是config.json文件里面的端口不是443，这种情况怎么解释？

443是nginx监听端口，config.json是实际v2ray运行的端口，用nginx是先到443端口然后再反代至v2ray那个端口的

v2ray本来支持就支持ss协议的，但是你这样做的话IP直接暴露了 该脚本的目的主要是隐藏真实IP 用域名

**Comment by charleslxa** [comment]
懂了。之前一直想通过博主的脚本搞V2ray多用户，试了很多方案不行（技术菜），后面就利用“v2ray本来支持就支持ss协议”这一特点来支持多用户。
