### ISSUE TITLE
[错误]  SSL 证书测试签发失败

### ISSUE THREAD

**Issue by dao3300** [wulabing/Xray_onekey#222]
装了多遍，总是有这个错误，请指教该怎么处理。
显示如下：

[OK]  安装 SSL 证书生成脚本依赖 完成
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   775    0   775    0     0   7007      0 --:--:-- --:--:-- --:--:--  7045
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  191k  100  191k    0     0   682k      0 --:--:-- --:--:-- --:--:--  684k
[Wed Mar 25 16:24:33 CST 2020] Installing from online archive.
[Wed Mar 25 16:24:33 CST 2020] Downloading https://github.com/acmesh-official/acme.sh/archive/master.tar.gz
[Wed Mar 25 16:24:34 CST 2020] Extracting master.tar.gz
[Wed Mar 25 16:24:34 CST 2020] Please install openssl first. ACME_OPENSSL_BIN=openssl
[Wed Mar 25 16:24:34 CST 2020] We need openssl to generate keys.
[Wed Mar 25 16:24:34 CST 2020] Pre-check failed, can not install.
[OK]  安装 SSL 证书生成脚本 完成
install.sh: line 463: /root/.acme.sh/acme.sh: No such file or directory
[错误]  SSL 证书测试签发失败

**Comment by dao3300** [comment]
如果单独安装证书 yum -y install epel-release；yum -y install certbot；certbot certonly --standalone -d example.com 后，再次一键安装，显示如下：

[OK]  SSL 证书测试签发成功，开始正式签发
[Wed Mar 25 16:54:44 CST 2020] Standalone mode.
[Wed Mar 25 16:54:44 CST 2020] Create account key ok.
[Wed Mar 25 16:54:44 CST 2020] Registering account
[Wed Mar 25 16:54:45 CST 2020] Registered
[Wed Mar 25 16:54:45 CST 2020] ACCOUNT_THUMBPRINT='ZBAZKUTpITL-C40OO4A34FuVdl6nOPoL1TXqS4CAlJM'
[Wed Mar 25 16:54:45 CST 2020] Creating domain key
[Wed Mar 25 16:54:45 CST 2020] The domain key is here: /root/.acme.sh/www..xyz_ecc/www..xyz.key
[Wed Mar 25 16:54:45 CST 2020] Single domain='www..xyz'
[Wed Mar 25 16:54:45 CST 2020] Getting domain auth token for each domain
[Wed Mar 25 16:54:45 CST 2020] Getting webroot for domain='www..xyz'
[Wed Mar 25 16:54:45 CST 2020] Verifying: www..xyz
[Wed Mar 25 16:54:45 CST 2020] Standalone mode server
[Wed Mar 25 16:54:49 CST 2020] Pending
[Wed Mar 25 16:54:51 CST 2020] Pending
[Wed Mar 25 16:54:54 CST 2020] Pending
[Wed Mar 25 16:54:56 CST 2020] Pending
[Wed Mar 25 16:54:58 CST 2020] www..xyz:Verify error:Fetching http://www..xyz/.well-known/acme-challenge/rM7w8UD3LJboR6upNoJscIJHm3bz4-Ckn_BMaFNUP3I: Timeout during connect (likely firewall problem)
[Wed Mar 25 16:54:58 CST 2020] Please add '--debug' or '--log' to check more details.
[Wed Mar 25 16:54:58 CST 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[错误]  SSL 证书生成失败

**Comment by charleslxa** [comment]
考虑重装系统再来安装一遍吗？

**Comment by dao3300** [comment]
做过许多遍了，包括重装系统，每次都是全新，包括升级、单独安装证书等等各种组合和顺序。系统用的是CentOS 7

**Comment by charleslxa** [comment]
为啥不是先安装一键脚本？我的服务器好像都没有升级(偷笑).....可以先试一试重装，之后就一键脚本，然后再升级

**Comment by xingcanli132** [comment]
443和80端口开放了吗 
### **likely firewall problem**

**Comment by dao3300** [comment]
早试过你的招数了，不行。不过目前装SSR了，能继续用，断流。暂时先不折腾V2ray了。

**Comment by ydzeal** [comment]
同问，好像是目录有错误

**Comment by ydzeal** [comment]
确实是目录有问题，把源代码的/.acme.sh改到你实际的目录就可以成功，亲测

**Comment by z1027001** [comment]
> 确实是目录有问题，把源代码的/.acme.sh改到你实际的目录就可以成功，亲测

大佬可以讲的稍微再详细一点吗 我今天也遇到这个问题了 Ubuntu 18.04 小白不是很懂怎么改目录

**Comment by wuchenchen** [comment]
Try 
#   iptables -F

可能本机网络防火墙有问题。

参考： 
1. https://github.com/acmesh-official/acme.sh/issues/203
2. https://superuser.com/questions/720851/connection-refused-vs-no-route-to-host

**Comment by JWX200126** [comment]
看一下是不是443端口没有打开

**Comment by hmtzmq** [comment]
> > 确实是目录有问题，把源代码的/.acme.sh改到你实际的目录就可以成功，亲测
> 
> 大佬可以讲的稍微再详细一点吗我今天也遇到这个问题了Ubuntu 18.04小白不是很懂怎么改目录

我也是新手，请问怎么改啊？

**Comment by hmtzmq** [comment]
> 确实是目录有问题，把源代码的/.acme.sh改到你实际的目录就可以成功，亲测

新手请教这个怎么改？

**Comment by zclsaber** [comment]
我也遇到了同样的错误。
脚本里面直接读取的$HOME值，因为是root用户纯净环境装的，所以手动修改$HOME为/root/实际上都指向了同一位置，重试后还是同样的错误。
参考下面这位说的，先尝试netstat -nlp 会发现80端口没打开。因为之前查看过机器的防火墙就忽略了这一点，部署在AWS上面的需要在AWS的group security里面开放入站流量才行。放行了80和443的TCP流量后再次运行脚本签发证书成功。

> Try
> 
> # iptables -F
> 可能本机网络防火墙有问题。
> 
> 参考：
> 
> 1. [acmesh-official/acme.sh#203](https://github.com/acmesh-official/acme.sh/issues/203)
> 2. https://superuser.com/questions/720851/connection-refused-vs-no-route-to-host

**Comment by micnp** [comment]
> Try
> 
> # iptables -F
> 可能本机网络防火墙有问题。
> 
> 参考：
> 
> 1. [acmesh-official/acme.sh#203](https://github.com/acmesh-official/acme.sh/issues/203)
> 2. https://superuser.com/questions/720851/connection-refused-vs-no-route-to-host

多谢  安全组设置了 但是机器防火墙还是有问题  现在可以了 弄了一个通宵了

**Comment by Huaweidev** [comment]
iptables -F命令有用，执行了之后立刻就成功申请证书了。
