### ISSUE TITLE
cloudflare DNS只能设置DNS ONLY吗？

### ISSUE THREAD

**Issue by exLuLu** [wulabing/Xray_onekey#228]
cloudflare DNS设为Proxied就不能连接了，那被墙了不就不能用了吗？怎么才能在Proxied下也能正常连接？

**Comment by Opdoop** [comment]
我遇到了同样的问题，请问你解决了吗？

**Comment by Opdoop** [comment]
按照这个wiki[wiki](https://github.com/wulabing/V2Ray_ws-tls_bash_onekey/wiki/%E5%A6%82%E4%BD%95%E6%9B%B4%E6%94%B9%E9%85%8D%E7%BD%AE%E4%BD%BF%E8%AF%A5%E8%84%9A%E6%9C%AC%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8-cloudflare-%E5%B5%8C%E5%A5%97)解决了问题。

**Comment by Opdoop** [comment]
又连不上了.....

**Comment by Opdoop** [comment]
按照wiki操作，端口改为默认端口就好了。

**Comment by Ancho5515** [comment]
> 按照wiki操作，端口改为默认端口就好了。

@Opdoop 你好，我按照wiki的操作还是不行，请问你说的端口改位默认端口具体是指什么？
server {
        listen 80;  //修改这里的端口为VPS默认端口吗?
        server_name xxx;
        return 301 xxx;
    }

**Comment by Opdoop** [comment]
@Ancho5515 

>建议单服务器仅搭建单个代理
本脚本默认安装最新版本的V2ray core
V2ray core 目前最新版本为 4.22.1（同时请注意客户端 core 的同步更新，需要保证客户端内核版本 >= 服务端内核版本）
建议使用默认的443端口作为连接端口
伪装内容可自行替换。

这里的，设为 443 端口。
