### ISSUE TITLE
安装 BBRplus版内核 - 4.14.129 出现的错误

### ISSUE THREAD

**Issue by linhaotao168** [wulabing/Xray_onekey#246]
Found linux image: /boot/vmlinuz-4.14.129-bbrplus
Found initrd image: /boot/initramfs-4.14.129-bbrplus.img
Found linux image: /boot/vmlinuz-0-rescue-c28d40cbc8e3adcb4e32d9779a77b39e
Found initrd image: /boot/initramfs-0-rescue-c28d40cbc8e3adcb4e32d9779a77b39e.img

**Comment by 2595133804** [comment]
这是成功了
