### ISSUE TITLE
版本1.1.3.4安装之后，3D元素周期表很多浏览器打不开

### ISSUE THREAD

**Issue by leefable** [wulabing/Xray_onekey#249]
用1.1.3.4脚本安装，伪装的网页3D元素周期表，大部分浏览器打不开
之前版本安装的貌似没有这个问题

**Comment by songhuyi** [comment]
> 用1.1.3.4脚本安装，伪装的网页3D元素周期表，大部分浏览器打不开
> 之前版本安装的貌似没有这个问题

可以试下把网页更换成自己在网上下载的网页模板
