### ISSUE TITLE
[错误]  SSL 证书测试签发失败 

### ISSUE THREAD

**Issue by divmid** [wulabing/Xray_onekey#252]
[Wed May 27 00:49:35 CST 2020] Using stage ACME_DIRECTORY: https://acme-staging-v02.api.letsencrypt.org/directory
[Wed May 27 00:49:36 CST 2020] Standalone mode.
[Wed May 27 00:49:36 CST 2020] Create account key ok.
[Wed May 27 00:49:36 CST 2020] Registering account
[Wed May 27 00:49:38 CST 2020] Registered
[Wed May 27 00:49:38 CST 2020] ACCOUNT_THUMBPRINT='LuuuueroaDszJNju4gboi-dp8hfp9xPcBLuyok5gMjw'
[Wed May 27 00:49:38 CST 2020] Creating domain key
[Wed May 27 00:49:38 CST 2020] The domain key is here: /root/.acme.sh/Y_ecc/Y.key
[Wed May 27 00:49:38 CST 2020] Single domain='Y'
[Wed May 27 00:49:38 CST 2020] Getting domain auth token for each domain
[Wed May 27 00:49:39 CST 2020] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:rejectedIdentifier",
  "detail": "Error creating new order :: Cannot issue for \"y\": Domain name needs at least one dot",
  "status": 400
}
[Wed May 27 00:49:39 CST 2020] Please add '--debug' or '--log' to check more details.
[Wed May 27 00:49:39 CST 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[错误]  SSL 证书测试签发失败

**Comment by cashbill2001** [comment]
我也是，应该是软件问题吧

**Comment by smarxpan** [comment]
你域名填了个Y，能签发成功就有鬼了。买域名了吗？配置DNS了吗？

**Comment by kebijuelun** [comment]
> 你域名填了个Y，能签发成功就有鬼了。买域名了吗？配置DNS了吗？

请问这里买域名和配置 DNS 的操作有参考吗？
