### ISSUE TITLE
v2ray的TLS流量可被简单特征码匹配精准识别

### ISSUE THREAD

**Issue by msn1983aa** [wulabing/Xray_onekey#254]
暂时解决方式：iptables规则可封禁所有v2ray的allowInsecureCiphers设置为false(默认设置)的出站TLS流量，而其他TLS流量不受影响:
iptables -I OUTPUT -m string --algo kmp --hex-string "|001ecca8cca9c02fc02bc030c02cc027c013c023c009c014c00a130113031302|" -j DROP

在新的版本释出之前，个人建议的缓解措施是客户端将allowInsecureCiphers设置为true。服务端建议可以拒绝所有具有此特征的TCP连接，以强迫所有客户端更新版本（但此举可能导致服务器遭到主动探测）。

**Comment by wulabing** [comment]
客户端内核跟进更新至4.23.2以上即可
