### ISSUE TITLE
建议增加进入管理脚本菜单的快捷方式

### ISSUE THREAD

**Issue by lariboo** [wulabing/Xray_onekey#258]
使用大佬的一键脚本搭建完毕后，如要再次进入管理脚本，需要粘贴wget -N --no-check-certificate -q -O install.sh "https://raw.githubusercontent.com/wulabing/V2Ray_ws-tls_bash_onekey/master/install.sh" && chmod +x install.sh && bash install.sh，不是很方便。建议登录SSH root账户后，输入v2ray直接进入管理脚本。

**Comment by yz7653886** [comment]
bash install.sh就行了... 前面是下载和权限
