### ISSUE TITLE
安装bbr之后就自动开启了吗 需要配置吗

### ISSUE THREAD

**Issue by supine-win** [wulabing/Xray_onekey#263]
还有个问题bbr安装的端口怎么配,不是很清楚.希望可以把这些加在read.me里谢谢

**Comment by jinwyp** [comment]
bbr是内核 和端口没关系 不用配置 ，但要启用bbr

推荐一个脚本 支持 trojan-go trojan v2ray 共存，升级和卸载,自动证书续签.可以修改root和ssh端口 支持WS+CDN https://github.com/jinwyp/one_click_script
