### ISSUE TITLE
安装 chrony 时间同步服务，请问如何解决

### ISSUE THREAD

**Issue by JLover0712** [wulabing/Xray_onekey#266]
[OK]  当前用户是root用户，进入安装流程
[OK]  当前系统为 Debian 9 stretch
Hit:1 http://security.debian.org stretch/updates InRelease
Hit:2 https://download.docker.com/linux/debian stretch InRelease
Ign:3 http://ftp.debian.org/debian stretch InRelease
Hit:4 http://ftp.debian.org/debian stretch-updates InRelease
Hit:5 http://ftp.debian.org/debian stretch Release
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
dbus is already the newest version (1.10.28-0+deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up chrony (3.0-4+deb9u2) ...
Job for chrony.service failed because the control process exited with error code.
See "systemctl status chrony.service" and "journalctl -xe" for details.
invoke-rc.d: initscript chrony, action "start" failed.
● chrony.service - chrony, an NTP client/server
   Loaded: loaded (/lib/systemd/system/chrony.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-07-03 21:30:38 CST; 26ms ago
     Docs: man:chronyd(8)
           man:chronyc(1)
           man:chrony.conf(5)
  Process: 2486 ExecStart=/usr/sbin/chronyd (code=exited, status=1/FAILURE)
      CPU: 12ms

Jul 03 21:30:38 vps81955493.hosteons.com systemd[1]: Starting chrony, an NTP client/server...
Jul 03 21:30:38 vps81955493.hosteons.com chronyd[2488]: chronyd version 3.0 starting (+CMDMON +NTP +REFCLOCK +RTC…DEBUG)
Jul 03 21:30:38 vps81955493.hosteons.com chronyd[2488]: Fatal error : adjtimex(0x8001) failed : Operation not permitted
Jul 03 21:30:38 vps81955493.hosteons.com chronyd[2486]: adjtimex(0x8001) failed : Operation not permitted
Jul 03 21:30:38 vps81955493.hosteons.com systemd[1]: chrony.service: Control process exited, code=exited status=1
Jul 03 21:30:38 vps81955493.hosteons.com systemd[1]: Failed to start chrony, an NTP client/server.
Jul 03 21:30:38 vps81955493.hosteons.com systemd[1]: chrony.service: Unit entered failed state.
Jul 03 21:30:38 vps81955493.hosteons.com systemd[1]: chrony.service: Failed with result 'exit-code'.
Hint: Some lines were ellipsized, use -l to show in full.
dpkg: error processing package chrony (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 chrony
E: Sub-process /usr/bin/dpkg returned an error code (1)
Failed to stop firewalld.service: Unit firewalld.service not loaded.
Failed to disable unit: No such file or directory
[OK]  firewalld 已关闭
Failed to stop ufw.service: Unit ufw.service not loaded.
Failed to disable unit: No such file or directory
[OK]  ufw 已关闭
Reading package lists... Done
Building dependency tree
Reading state information... Done
chrony is already the newest version (3.0-4+deb9u2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up chrony (3.0-4+deb9u2) ...
Job for chrony.service failed because the control process exited with error code.
See "systemctl status chrony.service" and "journalctl -xe" for details.
invoke-rc.d: initscript chrony, action "start" failed.
● chrony.service - chrony, an NTP client/server
   Loaded: loaded (/lib/systemd/system/chrony.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-07-03 21:30:40 CST; 12ms ago
     Docs: man:chronyd(8)
           man:chronyc(1)
           man:chrony.conf(5)
  Process: 2735 ExecStart=/usr/sbin/chronyd (code=exited, status=1/FAILURE)
      CPU: 12ms

Jul 03 21:30:40 vps81955493.hosteons.com systemd[1]: Starting chrony, an NTP client/server...
Jul 03 21:30:40 vps81955493.hosteons.com chronyd[2737]: chronyd version 3.0 starting (+CMDMON +NTP +REFCLOCK +RTC…DEBUG)
Jul 03 21:30:40 vps81955493.hosteons.com chronyd[2737]: Fatal error : adjtimex(0x8001) failed : Operation not permitted
Jul 03 21:30:40 vps81955493.hosteons.com chronyd[2735]: adjtimex(0x8001) failed : Operation not permitted
Jul 03 21:30:40 vps81955493.hosteons.com systemd[1]: chrony.service: Control process exited, code=exited status=1
Jul 03 21:30:40 vps81955493.hosteons.com systemd[1]: Failed to start chrony, an NTP client/server.
Jul 03 21:30:40 vps81955493.hosteons.com systemd[1]: chrony.service: Unit entered failed state.
Jul 03 21:30:40 vps81955493.hosteons.com systemd[1]: chrony.service: Failed with result 'exit-code'.
Hint: Some lines were ellipsized, use -l to show in full.
dpkg: error processing package chrony (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 chrony
E: Sub-process /usr/bin/dpkg returned an error code (1)
[错误]  安装 chrony 时间同步服务  失败

**Comment by ziggyxp** [comment]
同样问题，一起求助

**Comment by Alvin9999** [comment]
CentOS7 64位同样的问题

**Comment by erheeeee** [comment]
debian10 buster 同样的问题，chronyd无法启动adjtimex(0x8001) failed : Operation not permitted
是openvz架构 vps的问题吗？

**Comment by Busui** [comment]
查看是否存在/var/lib/dpkg/info，如果没有，mkdir /var/lib/dpkg/info即可。

**Comment by ziggyxp** [comment]
已解决，谢谢哈哈哈


在 2020年11月8日 11:17，lovekernel<notifications@github.com> 写道：


查看是否存在/var/lib/dpkg/info，如果没有，mkdir /var/lib/dpkg/info即可。
