### ISSUE TITLE
 域名dns解析IP与本机IP 不匹配

### ISSUE THREAD

**Issue by eos1d3** [wulabing/Xray_onekey#269]
此脚本一定要用域名带有 www, 不然即使本机IP没错也会当错。

比如 mydomain.com 就会报错
而www.mydoain.com就没报错

但两者的IP脚本运行时显示都没错。

**Comment by momohikari** [comment]
如果你使用的是cloudflare，去看看有没有将代理状态设为仅限Dns

**Comment by eos1d3** [comment]
都說了腳本運行時，腳本自己域名解析顯示的IP都是對的。但就是報錯說不對。

請看原問題。有www和沒www的域名都顯示相同IP, 只是腳本對沒www的域名輸入才出錯。

**Comment by jchang** [comment]
我也发现了，Cloudflare DNS Only。
自己 ping 一下域名看看解析对不对就行了

**Comment by jchang** [comment]
我也发现了，用的是 Cloudflare DNS Only。
自己 ping 一下域名看看解析对不对就行了
