### ISSUE TITLE
请问如何修改 伪装网站默认地址呢 ，安装宝塔感觉有冲突

### ISSUE THREAD

**Issue by liu191388548** [wulabing/Xray_onekey#270]
宝塔安装网站无法响应，网址对应的是伪装地址

**Comment by jinwyp** [comment]
推荐一个终极脚本 支持 trojan-go trojan v2ray xray 共存,带可视化面板,升级和卸载,自动证书续签.可以修改root和ssh端口,支持WS+CDN，Vless和xtls 模式 https://github.com/jinwyp/one_click_script
