### ISSUE TITLE
证书只有三个月，可以自动更新么？

### ISSUE THREAD

**Issue by TrevoryZhou** [wulabing/Xray_onekey#272]
脚本可以自动更新证书么？还是需要手动命令更新？

**Comment by updater1234** [comment]
可以自动更新

**Comment by jinwyp** [comment]
一般 acme.sh 申请的证书自带crontab 定时脚本自动更新 

推荐一个脚本 支持 trojan-go trojan v2ray 共存，升级和卸载,自动证书续签.可以修改root和ssh端口 支持WS+CDN https://github.com/jinwyp/one_click_script
