### ISSUE TITLE
配置完成之后如何让修改域名？

### ISSUE THREAD

**Issue by wjk199511140034** [wulabing/Xray_onekey#284]
服务器默默运行一年多了，因为老域名快到期了，正好换成之前撸的xyz域名，
都有哪些地方需要修改呢。。。。

**Comment by jinwyp** [comment]
很多地方
1 acme.sh 脚本要重新运行 申请证书 
2 nginx 配置
3 v2ray 配置

推荐一个脚本 支持 trojan-go trojan v2ray 共存，升级和卸载,自动证书续签.可以修改root和ssh端口 支持WS+CDN https://github.com/jinwyp/one_click_script

**Comment by wjk199511140034** [comment]
需要修改的文件有：
/usr/local/vmess_qr.json
/etc/nginx/conf/conf.d/v2ray.conf
最后reboot一下，按理说还需要更新下下证书的，但是reboot之后意外的更改成功了
查看一下key的修改日期也变成了刚才，总之凑合用吧。。。

**Comment by lianweiming** [comment]
经测试，最新xray基础下修改域名，需要修改：
1.acme.sh重新签发、安装证书
2.nginx配置新域名、重启
3.xray修改域名、重启，xray域名配置在/usr/local/etc/xray/domain文件里
