### ISSUE TITLE
能否适配宝塔面板安装的nginx，或不安装nginx只配置v2ray

### ISSUE THREAD

**Issue by liwenjie119** [wulabing/Xray_onekey#285]
如果不好自动配置宝塔的nginx，可行的方案是把网站源码放在/www/wwwroot/域名，然后正常配置v2ray，然后说明需要在nginx添加的配置，配置完成后用户自己重启v2ray就行

**Comment by UESTCHenry** [comment]
+1

**Comment by Mmxp** [comment]
我来适配吧，然后交个pr，可以嘛@wulabing

**Comment by jinwyp** [comment]
推荐一个终极脚本 支持 trojan-go trojan v2ray xray 共存,带可视化面板,升级和卸载,自动证书续签.可以修改root和ssh端口,支持WS+CDN，Vless和xtls 模式 https://github.com/jinwyp/one_click_script
