### ISSUE TITLE
[Warning] [3003743318]请教一下大神，实在不知道什么情况。同样的方法以前能用现在不能用，不太明白

### ISSUE THREAD

**Issue by doegeenon** [wulabing/Xray_onekey#286]
2020/10/09 05:08:52 [Warning] [3003743318] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vless/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://doegeenon.ga/c0d195019d456/): 502 Bad Gateway > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by qinyinglun** [comment]
我也是一样，重装系统重新搭建都用不了了。

**Comment by stcharlesc** [comment]
我这也出现这种情况，使用其他的脚本安装就可以使用

**Comment by dakezuo** [comment]
我也是这个问题，加了tls就不行，不知道为啥，已经换了3波证书了都一样
