### ISSUE TITLE
VLess+websocket+TLS+Nginx+Website客户端配置不能填IP

### ISSUE THREAD

**Issue by wyl2000** [wulabing/Xray_onekey#295]
VLess+websocket+TLS+Nginx+Website V2Ray 4.31.3在IP那只能真域名，填IP就不能连网
vmess+websocket+TLS+Nginx+Website V2Ray 4.31.3在IP那可以IP或者域名
用的免费域名有可能不稳定，自己用，有时想直接IP，发现用vless的不能填IP搞不懂，不过用域名这个VLess方式速度可怕，提升太明显了。两种方式都可以用域名访问元素周期表网页，IP不能。这是一个bug吗？

**Comment by jinwyp** [comment]
推荐一个终极脚本 支持 trojan-go trojan v2ray 共存,带可视化面板,升级和卸载,自动证书续签.可以修改root和ssh端口,支持WS+CDN，Vless和xtls 模式 https://github.com/jinwyp/one_click_script
