### ISSUE TITLE
Vless 脚本选择的是1安装，在CF上设置小黄云之后就不能用，小灰云可以用

### ISSUE THREAD

**Issue by Stonewalling** [wulabing/Xray_onekey#296]
Vless 脚本选择的是1安装，在CF上设置小黄云之后就不能用，小灰云可以用

**Comment by l123456789jy** [comment]
+1 今天最新版本页复现了，开启CDN就不行了

**Comment by jinwyp** [comment]
推荐一个终极脚本 支持 trojan-go trojan v2ray xray 共存,带可视化面板,升级和卸载,自动证书续签.可以修改root和ssh端口,支持WS+CDN，Vless和xtls 模式 https://github.com/jinwyp/one_click_script

**Comment by wjk199511140034** [comment]
+1 今天从v2ray换成了xray，开了cf代理就不能用了，关了代理纯解析就正常。。。
cf的设置没变过，之前用v2ray走代理正常使用

**Comment by KukiSa** [comment]
@wjk199511140034 Because option 1 will make the server work in XTLS mode instead of WebSocket mode, Cloudflare based on standard TLS and WebSocket transmission will not work for it.

**Comment by KukiSa** [comment]
@wjk199511140034 If you want to use Cloudflare to transfer your traffic, please choose option 2: ``安装 Xray (VLESS + TCP + XTLS / TLS + Nginx 及 VLESS + TCP + TLS + Nginx + WebSocket 回落并存模式)``.
