### ISSUE TITLE
能不能适配宝塔Nginx支持，安装的时候会直接把宝塔的端口kill掉

### ISSUE THREAD

**Issue by wdsjxh** [wulabing/Xray_onekey#297]
如题

**Comment by jinwyp** [comment]
推荐一个终极脚本 支持 trojan-go trojan v2ray 共存,带可视化面板,升级和卸载,自动证书续签.可以修改root和ssh端口,支持WS+CDN，Vless和xtls 模式 https://github.com/jinwyp/one_click_script

**Comment by wdsjxh** [comment]
我回头看看



---原始邮件---
发件人: "JinWYP"<notifications@github.com&gt;
发送时间: 2020年11月4日(周三) 晚上9:33
收件人: "wulabing/V2Ray_ws-tls_bash_onekey"<V2Ray_ws-tls_bash_onekey@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"wdsjxh"<1739642302@qq.com&gt;;
主题: Re: [wulabing/V2Ray_ws-tls_bash_onekey] 能不能适配宝塔Nginx支持，安装的时候会直接把宝塔的端口kill掉 (#297)




 
推荐一个终极脚本 支持 trojan-go trojan v2ray 共存,带可视化面板,升级和卸载,自动证书续签.可以修改root和ssh端口,支持WS+CDN，Vless和xtls 模式 https://github.com/jinwyp/one_click_script

**Comment by AAkira45** [comment]
@jinwyp 可以再支持一下xray-core 现在v2和xtls这块分开了

**Comment by jinwyp** [comment]
> @jinwyp 可以再支持一下xray-core 现在v2和xtls这块分开了

我的脚本已经支持了 xray 和direct 模式了
