### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Vzz1c** [wulabing/Xray_onekey#300]
1

**Comment by Vzz1c** [comment]
香港换美国地区,自己搭建的web工程都可以正常访问,vpn真就一点速度没有,还是换回bbr了

**Comment by AAkira45** [comment]
这和脚本及V2无关，和VPS所在的地区网络有关系，这种也只能联系服务器提供商解决

**Comment by NetHeritage** [comment]
这个脚本是为一般需求的普通用户准备的，你想要其他的功能，可以自己去写一个。
其次，速度快慢，与服务器性能、线路及你本地的带宽和设备性能有关系，而与脚本无关。
再者，issue区是反馈bug和讨论开发的地方，不是发这种信息的地方。

**Comment by wanghaocun** [comment]
> 用bbr优化后加速看个youtube还是可以的,自己加了白名单过滤国内的网站,全球通基本都是秒开就是网络波动有点大,看到作者这个我还以为网络稳定下来.好家伙,打开个google都费劲,根本没法用,打开国内更加慢,为啥不设置和白名单??真就能连就行不考虑效果??

你这网络环境跟脚本有什么关系  人家只负责环境安装  网络波动和卡顿问题是你vps服务商的问题  搞清楚具体关系好吧

**Comment by jinwyp** [comment]
推荐一个终极脚本 支持 trojan-go trojan v2ray xray 共存,带可视化面板,升级和卸载,自动证书续签.可以修改root和ssh端口,支持WS+CDN，Vless和xtls 模式 https://github.com/jinwyp/one_click_script
