### ISSUE TITLE
请问题，能不能开发问下要不要配置证书？

### ISSUE THREAD

**Issue by 1371030** [wulabing/Xray_onekey#301]
请问题，能不能开发问下要不要配置证书？我已经配好域名和证书了，还是下载了好多安装的程序

**Comment by jinwyp** [comment]
这个可以 不装证书
推荐一个终极脚本 支持 trojan-go trojan v2ray 共存,带可视化面板,升级和卸载,自动证书续签.可以修改root和ssh端口,支持WS+CDN，Vless和xtls 模式 https://github.com/jinwyp/one_click_script

**Comment by 1371030** [comment]
@jinwyp 谢谢了，我的是配置好了nginx+stl 了，只要配置v2ray就行了，这个脚本重写了nginx systemed的启动脚本，导致我安装后不能启动nginx。
