### ISSUE TITLE
请问各位高手如何修改默认的元素周期表网页呢？怎么替换

### ISSUE THREAD

**Issue by 3dkkk** [wulabing/Xray_onekey#306]
在哪里可以修改，貌似找不到后台管理页面啊，求助？？

**Comment by rfiacne** [comment]
说明里有呀。
Web 目录：/home/wwwroot/3DCEList
替换一下里面的内容就好了

**Comment by 3dkkk** [comment]
非常感谢，直接往里面一丢是吧？？
要是vless能和wordpress一块用就好了😁！

**Comment by rfiacne** [comment]
wordpress还要装mysql和php吧。你看看脚本有没装？没装的话，自己装一下

**Comment by 3dkkk** [comment]
太难了，弄不好，有人弄成功的能同时用吗！

**Comment by 3dkkk** [comment]
> 说明里有呀。
> Web 目录：/home/wwwroot/3DCEList
> 替换一下里面的内容就好了

直接把文件夹丢进去，其他的都不用改吗？我换了一个怎么不行啊？
