### ISSUE TITLE
SSL证书生成失败

### ISSUE THREAD

**Issue by fayewonghz** [wulabing/Xray_onekey#312]
`[Sun Jan 31 15:21:26 UTC 2021] Single domain='vv.huangyue369.xyz'
[Sun Jan 31 15:21:26 UTC 2021] Getting domain auth token for each domain
[Sun Jan 31 15:21:27 UTC 2021] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many certificates already issued for exact set of domains: vv.huang369.xyz: see https://letsencrypt.org/docs/rate-limits/",
  "status": 429
}
[Sun Jan 31 15:21:27 UTC 2021] Please add '--debug' or '--log' to check more details.
[Sun Jan 31 15:21:27 UTC 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[错误]  SSL 证书生成失败
`
在其它VPS没问题，在vultr换了几个系统都出现这个问题，域名解释正常的

**Comment by PDSCi996** [comment]
我以前遇到一种情况是解析网站每周有固定的次数限制，超出后申请会失败，等到下一周就可以了，活着换个域名解析。

**Comment by fordiy** [comment]
换了很多域名都是这样[ERROR] SSL 证书生成失败，安装脚本在 
Canonical-Ubuntu-20.04-Minimal-2021.04.19问题

**Comment by KukiSa** [comment]
@fordiy Please search "甲骨文云关闭防火墙" and follow the relevant tutorials.

**Comment by OrangeKnife** [comment]
试试安装ping
sudo apt install iputils-ping
