### ISSUE TITLE
VLESS+TCP+XTLS+Nginx搭建完成生成的二维码所有客户端扫码失败

### ISSUE THREAD

**Issue by f2sky** [wulabing/Xray_onekey#326]
使用一键脚本搭建完成之后，打开提供的二维码，分别使用iOS（shadowrocket）、macOS（v2rayU）、安卓（v2rayNG）客户端扫描，没有一个成功。

使用链接导入也多数客户端有问题，最后不得不手动添加成功。

求问，这是二维码的问题，还是客户端扫码的问题？

**Comment by wulabing** [comment]
VLESS 的 导入链接规范目前大部分客户端还未适配，需要等待后续适配
目前 V2rayN 4.12 版本及 V2rayNG pre-release 版可以正常导入

**Comment by jeasonliang** [comment]
最新的小火箭也不行

**Comment by wulabing** [comment]
> 最新的小火箭也不行

小火箭那面问过作者，短期内不跟进

**Comment by jeasonliang** [comment]
> > 最新的小火箭也不行
> 
> 小火箭那面问过作者，短期内不跟进

嗯 ！ 感谢感谢！

**Comment by jeasonliang** [comment]
> > 最新的小火箭也不行
> 
> 小火箭那面问过作者，短期内不跟进

晚上回去测试下梅林的可以用不
