### ISSUE TITLE
[BUG]在已经安装了v2ray的机器下运行脚本会提示"Nginx config modify 失败"

### ISSUE THREAD

**Issue by pkgod** [wulabing/Xray_onekey#329]
感谢你向 Xray_onekey 提交 issue！

./install.sh: line 306: cd: /etc/nginx/conf.d/: No such file or directory
sed: can't read /etc/nginx/conf.d/www.msgeek.xyz.conf: No such file or directory
[ERROR]  Nginx config modify 失败

**Comment by wulabing** [comment]
@pkgod 请按照 issue template 填写必要的信息，感谢理解
