### ISSUE TITLE
整个安装过程未见异常，后台查询未进有xray进程，连接也不通

### ISSUE THREAD

**Issue by relidaning** [wulabing/Xray_onekey#333]
开始是因为有本地进程占用80端口，后来改掉再次执行脚本，未见异常信息，但是连接不成功，查看连接日志后台没信息，连接外网页面不通但是会自动下载一个genarate_204的文件，systemctl xray start执行也没报错，ps查询未见xray进程

请问这是什么问题

**Comment by jiuqi9997** [comment]
@relidaning systemctl xray start执行也没报错就见鬼了

**Comment by relidaning** [comment]
哈哈，写反了，多执行脚本后来就可以了，应该是之前有端口占用安装失败后来有程序没卸载干净导致的，谢谢老哥
