### ISSUE TITLE
[BUG] NAT机使用Let's SSL签发证书成功，验证证书失败

### ISSUE THREAD

**Issue by edmund-zhao** [wulabing/Xray_onekey#339]
### 服务运行情况

`sysemctl status xray` 
显示xray运行正常

### 环境 Environment

* 操作系统
*  Centos 8 OpenZv虚拟化
……
* 是否全新安装
* 是
······
* 其他可以补充的信息
* 按照配置 /usr/local/etc/xray/config.json 文件，可以正常使用
……

### 说明 Description

服务运行正常，但是脚本会在申请证书完成后，验证证书那一步报错。
通过查询 xray 的配置文件，可以正常连接（脚本生成的配置文件）

### 重现问题的具体步骤

1. 将服务器的443、80的端口不公开，在防火墙设置成全部IP禁止进入
2. 安装脚本，选择配置二

### 可能的解决方案 Possible Solution

可以在sh脚本之中添加跳过验证Let's ssl的验证证书步骤，从而避免脚本报错

**Comment by Butterflyflower** [comment]
@edmund-zhao 请手动安装xray

**Comment by edmund-zhao** [comment]
> @edmund-zhao 请手动安装xray

手动安装无问题，脚本安装除了最后一步，无法显示vless://链接以外，也无问题，只是希望可以添加一个跳过let's ssl verify ssl的功能
