### ISSUE TITLE
安装过程中有一段密集报错

### ISSUE THREAD

**Issue by Gslw** [wulabing/Xray_onekey#341]
install.sh: line 97: curl: command not found
install.sh: line 97: sudo: command not found
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Get:4 http://nginx.org/packages/debian buster InRelease [3,589 B]
Err:4 http://nginx.org/packages/debian buster InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ABF5BD827BD9BF62
Reading package lists... Done
W: GPG error: http://nginx.org/packages/debian buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ABF5BD827BD9BF62
E: The repository 'http://nginx.org/packages/debian buster InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree
Reading state information... Done
dbus is already the newest version (1.12.20-0+deb10u1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Failed to stop firewalld.service: Unit firewalld.service not loaded.
Failed to disable unit: Unit file firewalld.service does not exist.
Failed to stop nftables.service: Unit nftables.service not loaded.
Failed to disable unit: Unit file nftables.service does not exist.
Failed to stop ufw.service: Unit ufw.service not loaded.
Failed to disable unit: Unit file ufw.service does not exist.

**Comment by KukiSa** [comment]
@Gslw 请执行 apt-get upgrade && apt-get update

**Comment by Gslw** [comment]
@KukiSa 这就是脚本安装过程中的apt-get upgrade && apt-get update报错

**Comment by KukiSa** [comment]
@Gslw 请加群讨论 t.me/wulabing_v2ray

**Comment by Gslw** [comment]
这群怎么加，你给的那个命令真的不行，一样的报错。

root@Htmwait:~# apt-get upgrade && apt-get update
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  linux-image-amd64
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Get:4 http://nginx.org/packages/debian buster InRelease [3,589 B]
Err:4 http://nginx.org/packages/debian buster InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ABF5BD827BD9BF62
Reading package lists... Done
W: GPG error: http://nginx.org/packages/debian buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ABF5BD827BD9BF62
E: The repository 'http://nginx.org/packages/debian buster InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@Htmwait:~#

**Comment by Gslw** [comment]
这群怎么加，你给的那个命令真的不行，一样的报错。

root@Htmwait:~# apt-get upgrade && apt-get update
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  linux-image-amd64
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Get:4 http://nginx.org/packages/debian buster InRelease [3,589 B]
Err:4 http://nginx.org/packages/debian buster InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ABF5BD827BD9BF62
Reading package lists... Done
W: GPG error: http://nginx.org/packages/debian buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ABF5BD827BD9BF62
E: The repository 'http://nginx.org/packages/debian buster InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@Htmwait:~#

**Comment by Gslw** [comment]
百度到了解决办法

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ABF5BD827BD9BF62
