### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PalenCent** [wulabing/Xray_onekey#344]
感谢你向 Xray_onekey 提交 issue！

在提交之前，请确认：

- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！
- [ ] 我已经在Issue中找过我要提出的问题
- [x] 我已经使用最新版本的脚本测试过，问题依旧存在
- [x] 我已经仔细看过脚本报错提示并无法自行解决问题

请注意，如果你并没有遵照这个 issue template 填写内容，我们将看心情关闭这个 issue。

------------------------------------------------------------------

### 服务运行情况

请运行命令 service xray status 并粘贴输出：

```
![image](https://user-images.githubusercontent.com/45139699/115118767-74207000-9fd7-11eb-9d95-a853bed1c434.png)

```
请运行命令 service nginx status 并粘贴输出：
```
![image](https://user-images.githubusercontent.com/45139699/115118789-8c908a80-9fd7-11eb-9038-5961cc29e235.png)
```

### 环境 Environment

* 操作系统
ubuntu20.04
……
* 是否全新安装
是
……
* 如果不是全新安装，有无安装其他软件（宝塔，Nginx等）
……
* 其他可以补充的信息
access.log有输出
![image](https://user-images.githubusercontent.com/45139699/115118824-bd70bf80-9fd7-11eb-9f07-90bb04fd319d.png)

……

**Comment by wulabing** [comment]
没有具体的问题说明
