### ISSUE TITLE
TLS及WS_TLS节点可正常联网，XTLS节点无法联网

### ISSUE THREAD

**Issue by ni7ht** [wulabing/Xray_onekey#345]
感谢你向 Xray_onekey 提交 issue！

在提交之前，请确认：

- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！
- [x] 我已经在Issue中找过我要提出的问题
- [x] 我已经使用最新版本的脚本测试过，问题依旧存在
- [x] 我已经仔细看过脚本报错提示并无法自行解决问题

请注意，如果你并没有遵照这个 issue template 填写内容，我们将看心情关闭这个 issue。

------------------------------------------------------------------

### 服务运行情况

请运行命令 service xray status 并粘贴输出：
```

将输出粘贴在这里
```
Redirecting to /bin/systemctl status xray.service
● xray.service - Xray Service
   Loaded: loaded (/etc/systemd/system/xray.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/xray.service.d
           └─10-donot_touch_single_conf.conf
   Active: active (running) since Tue 2021-04-20 15:26:20 CST; 13min ago
     Docs: https://github.com/xtls
 Main PID: 1240 (xray)
    Tasks: 8 (limit: 5676)
   Memory: 23.5M
   CGroup: /system.slice/xray.service
           └─1240 /usr/local/bin/xray run -config /usr/local/etc/xray/config.json

Apr 20 15:26:20 instance-20210418-2258 systemd[1]: Started Xray Service.
Apr 20 15:26:22 instance-20210418-2258 xray[1240]: Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 linux/amd64)
Apr 20 15:26:22 instance-20210418-2258 xray[1240]: A unified platform for anti-censorship.
Apr 20 15:26:22 instance-20210418-2258 xray[1240]: 2021/04/20 15:26:22 [Info] infra/conf/serial: Reading config: /usr/local/etc/xray/config.json

请运行命令 service nginx status 并粘贴输出：
```
将输出粘贴在这里
```
[root@instance-20210418-2258 ~]# service nginx status
Redirecting to /bin/systemctl status nginx.service
● nginx.service - nginx - high performance web server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2021-04-20 15:44:46 CST; 4s ago
     Docs: http://nginx.org/en/docs/
  Process: 1979 ExecStart=/usr/sbin/nginx -c /etc/nginx/nginx.conf (code=exited, status=0/SUCCESS)
 Main PID: 1980 (nginx)
    Tasks: 2 (limit: 5676)
   Memory: 3.5M
   CGroup: /system.slice/nginx.service
           ├─1980 nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.conf
           └─1981 nginx: worker process

Apr 20 15:44:46 instance-20210418-2258 systemd[1]: Starting nginx - high performance web server...
Apr 20 15:44:46 instance-20210418-2258 systemd[1]: Started nginx - high performance web server.

### 环境 Environment

* 操作系统
Centos 8
* 是否全新安装
* 是
* 如果不是全新安装，有无安装其他软件（宝塔，Nginx等）
……
* 其他可以补充的信息
#访问日志只有TLS及WS_TLS访问记录无XTLS记录：
2021/04/20 14:51:41 114.246.35.154:39170 accepted tcp:www.google.com:443
2021/04/20 14:51:42 114.246.35.154:44168 accepted tcp:www.google.com:443
2021/04/20 14:59:37 114.246.35.154:44347 accepted tcp:www.google.com:443
2021/04/20 14:59:37 114.246.35.154:29080 accepted tcp:www.google.com:443
2021/04/20 15:11:59 114.246.35.154:18536 accepted tcp:www.google.com:443
2021/04/20 15:11:59 114.246.35.154:48416 accepted tcp:www.google.com:443
2021/04/20 15:23:56 114.246.35.154:9038 accepted tcp:www.google.com:443
2021/04/20 15:23:56 114.246.35.154:19811 accepted tcp:www.google.com:443
2021/04/20 15:28:09 114.246.35.154:44543 accepted tcp:www.google.com:443
2021/04/20 15:28:09 114.246.35.154:44540 accepted tcp:www.google.com:443

#错误日志
2021/04/20 15:28:10 [Warning] [3328509892] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:60000 > common/retry: [dial tcp 127.0.0.1:60000: connect: connection refused] > common/retry: all retry attempts failed
2021/04/20 15:28:11 [Warning] [2255801966] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:60000 > common/retry: [dial tcp 127.0.0.1:60000: connect: connection refused] > common/retry: all retry attempts failed
2021/04/20 15:32:59 [Warning] [4024131494] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:60000 > common/retry: [dial tcp 127.0.0.1:60000: connect: connection refused] > common/retry: all retry attempts failed
2021/04/20 15:33:00 [Warning] [3504098145] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:60000 > common/retry: [dial tcp 127.0.0.1:60000: connect: connection refused] > common/retry: all retry attempts failed
2021/04/20 15:34:28 [Warning] [3592848556] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:60000 > common/retry: [dial tcp 127.0.0.1:60000: connect: connection refused] > common/retry: all retry attempts failed
2021/04/20 15:34:30 [Warning] [1978581551] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:60000 > common/retry: [dial tcp 127.0.0.1:60000: connect: connection refused] > common/retry: all retry attempts failed
2021/04/20 15:35:33 [Warning] [406529811] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:60000 > common/retry: [dial tcp 127.0.0.1:60000: connect: connection refused] > common/retry: all retry attempts failed
2021/04/20 15:35:34 [Warning] [3585090330] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:60000 > common/retry: [dial tcp 127.0.0.1:60000: connect: connection refused] > common/retry: all retry attempts failed
2021/04/20 15:35:46 [Warning] [3518777330] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:60000 > common/retry: [dial tcp 127.0.0.1:60000: connect: connection refused] > common/retry: all retry attempts failed
2021/04/20 15:35:47 [Warning] [1007442007] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:60000 > common/retry: [dial tcp 127.0.0.1:60000: connect: connection refused] > common/retry: all retry attempts failed

#防火墙状态

#firewalld
[root@instance-20210418-2258 ~]# service firewalld status
Redirecting to /bin/systemctl status firewalld.service
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:firewalld(1)
[root@instance-20210418-2258 ~]# 

#iptables
[root@instance-20210418-2258 ~]# service firewalld status
Redirecting to /bin/systemctl status firewalld.service
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:firewalld(1)
[root@instance-20210418-2258 ~]# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
[root@instance-20210418-2258 ~]# 

### 说明 Description

TLS及WS_TLS节点可正常联网，XTLS节点无法联网
时区已经改为上海，第一次查看nginx未运行，手动运行34更新xray core后nginx启动，XTLS节点依旧无法联网。纯小白求助求助。
请输入数字：34
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   141  100   141    0     0    159      0 --:--:-- --:--:-- --:--:--   159
100 29581  100 29581    0     0  23836      0  0:00:01  0:00:01 --:--:--  186k
info: No new version. The current version of Xray is v1.4.2 .
[OK]  Nginx 启动 完成 
[OK]  Xray 启动 完成 
[root@instance-20210418-2258 ~]# 

### 重现问题的具体步骤

此问题一直存在。

**我预期会发生……？**

**实际上发生了什么？**

**Comment by wulabing** [comment]
留意客户端使用的内核
XTLS 需要使用 xray 内核，如果是V2RAYN/NG客户端的话，可以在设置里面切换使用的内核，然后重新下载内核，重启客户端使用

**Comment by ni7ht** [comment]
> 留意客户端使用的内核
> XTLS 需要使用 xray 内核，如果是V2RAYN客户端的话，可以在设置里面切换使用的内核，然后重新下载内核，重启客户端使用

非常感谢，搞定了，
![image](https://user-images.githubusercontent.com/37174285/115364245-c8a13680-a1f5-11eb-8417-d98a71593960.png)

**Comment by vztimeout** [comment]
> 留意客户端使用的内核 XTLS 需要使用 xray 内核，如果是V2RAYN客户端的话，可以在设置里面切换使用的内核，然后重新下载内核，重启客户端使用

v2raya怎么切换成XRAY内核？求指导。。
