### ISSUE TITLE
v2rayNG: context deadline exceeded

### ISSUE THREAD

**Issue by XiaoNaoXu** [wulabing/Xray_onekey#348]
我也出现了这个问题。我用的是VLESS，应该不需要同步时间吧？只要是日本的服务器就会出现这样的问题，我用英国服务器就是正常的，
这是一次完整的LOG：
05-06 13:41:52.713 I/GoLog   ( 3503): Using Prepared: 服务器IP地址
05-06 13:41:58.251 D/com.v2ray.ang( 3503): SCREEN_OFF, stop querying stats
05-06 13:42:02.348 I/GoLog   ( 3503): Not Using Prepared: tcp,203.205.235.218:8081
05-06 13:42:02.348 I/GoLog   ( 3503): tcp:127.0.0.1:43980 accepted tcp:203.205.235.218:8081 [socks -> direct]
05-06 13:42:02.548 D/com.v2ray.ang( 3503): SCREEN_ON, start querying stats
05-06 13:42:03.574 I/GoLog   ( 3503): Not Using Prepared: tcp,203.205.235.218:8081
05-06 13:42:03.574 I/GoLog   ( 3503): tcp:127.0.0.1:43986 accepted tcp:203.205.235.218:8081 [socks -> direct]
05-06 13:42:03.593 D/com.v2ray.ang( 3503): measureV2rayDelay: go.Universe$proxyerror: Get "http://www.google.com/generate_204": context deadline exceeded

_Originally posted by @XiaoNaoXu in https://github.com/wulabing/Xray_onekey/issues/340#issuecomment-833245167_

**Comment by KukiSa** [comment]
@XiaoNaoXu According to the log, I think your client version is too old, please update v2rayNG at https://github.com/2dust/v2rayNG

**Comment by XiaoNaoXu** [comment]
我换成了最新的1.6.6，还是不行，但是英国的服务器还是好的，日本的服务器还是不行。


--------- beginning of main
05-06 15:14:32.618 I/GoLog   (32611): udp:127.0.0.1:44705 accepted udp:1.1.1.1:53 [socks >> proxy]
05-06 15:14:32.629 I/GoLog   (32611): udp:127.0.0.1:44696 accepted udp:1.1.1.1:53 [socks >> proxy]
05-06 15:14:33.992 I/GoLog   (32611): Using Prepared: 服务器IP
05-06 15:14:35.739 I/GoLog   (32611): Using Prepared: 服务器IP
05-06 15:14:36.530 I/GoLog   (32611): udp:127.0.0.1:40756 accepted udp:1.1.1.1:53 [socks >> proxy]
05-06 15:14:37.623 I/GoLog   (32611): udp:127.0.0.1:42220 accepted udp:114.114.114.114:53 [socks >> proxy]
05-06 15:14:37.641 I/GoLog   (32611): udp:127.0.0.1:39992 accepted udp:114.114.114.114:53 [socks >> proxy]
05-06 15:14:39.792 I/GoLog   (32611): Using Prepared: 服务器IP
05-06 15:14:39.852 I/GoLog   (32611): fdConn unix.Connect err, Close Fd: 93 Err: connection timed out
05-06 15:14:40.912 I/GoLog   (32611): Using Prepared: 服务器IP
05-06 15:14:41.532 I/GoLog   (32611): udp:127.0.0.1:49333 accepted udp:114.114.114.114:53 [socks >> proxy]
05-06 15:14:42.939 I/GoLog   (32611): tcp:127.0.0.1:38112 accepted tcp:36.155.229.173:443 [socks >> proxy]
05-06 15:14:43.041 I/GoLog   (32611): Using Prepared: 服务器IP
05-06 15:14:43.777 I/GoLog   (32611): Using Prepared: 服务器IP
05-06 15:14:44.462 I/GoLog   (32611): fdConn unix.Connect err, Close Fd: 96 Err: connection timed out
05-06 15:14:44.695 I/GoLog   (32611): Using Prepared: 服务器IP
05-06 15:14:44.716 I/GoLog   (32611): fdConn unix.Connect err, Close Fd: 98 Err: connection timed out
05-06 15:14:45.127 I/GoLog   (32611): Using Prepared: 服务器IP
05-06 15:14:45.837 I/GoLog   (32611): Using Prepared: 服务器IP
05-06 15:14:49.283 D/com.v2ray.ang(32611): measureV2rayDelay: go.Universe$proxyerror: Get "http://www.google.com/generate_204": context deadline exceeded
05-06 15:14:52.749 I/GoLog   (32611): udp:127.0.0.1:48832 accepted udp:1.1.1.1:53 [socks >> proxy]
05-06 15:14:53.725 I/GoLog   (32611): udp:127.0.0.1:44607 accepted udp:1.1.1.1:53 [socks >> proxy]

**Comment by KukiSa** [comment]
@XiaoNaoXu Please execute \systemctl status xray\ on the server first or visit ping.pe to test the port of your server.

**Comment by XiaoNaoXu** [comment]
多谢提醒，找到原因了，手机和电脑的网络不同，配置的时候用的电脑来检测的IP没问题，但是手机是移动网，和服务器通信的丢包率高达90%多。。。我换个服务器，多谢了。

**Comment by XiaoNaoXu** [comment]
问题解决
