### ISSUE TITLE
为"outbounds"设置IPV6出栈规则后伪装页面无法正常显示。

### ISSUE THREAD

**Issue by freenaser** [wulabing/Xray_onekey#350]
RT. 设置好规则后运行systemctl restart xray代理运行正常，规则也运行正常，但是伪装页面手动访问后无页面出现。systemctl status xray无报错，reboot问题依旧，系统为CentOS。

**Comment by KukiSa** [comment]
@freenaser Please post the ``config.json`` after desensitization.

**Comment by freenaser** [comment]
> 
> 
> @freenaser Please post the `config.json` after desensitization.

[config.TXT](https://github.com/wulabing/Xray_onekey/files/6477015/config.TXT)
