### ISSUE TITLE
xtls不能开作，tls可以工作

### ISSUE THREAD

**Issue by amiriliao** [wulabing/Xray_onekey#376]
1/10/12 10:40:15 127.0.0.1:10861 accepted http://91.108.56.160:80/api [ykqswftcowloggm]
2021/10/12 10:40:15 127.0.0.1:1024 accepted //content-autofill.googleapis.com:443 [ykqswftcowloggm]
2021/10/12 10:40:16 [Warning] [416113270] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:8889->127.0.0.1:10861: wsasend: An established connection was aborted by the software in your host machine.
2021/10/12 10:40:16 127.0.0.1:5138 accepted http://matrix.dioco.io/mmd_YT_0 [ykqswftcowloggm]
2021/10/12 10:40:20 127.0.0.1:1044 accepted //wsv3-widget.aicoin.net.cn:443 [DIRECT]
2021/10/12 10:40:20 127.0.0.1:1051 accepted //91.108.56.160:443 [ykqswftcowloggm]
2021/10/12 10:40:20 127.0.0.1:1056 accepted http://91.108.56.160:80/api [ykqswftcowloggm]
2021/10/12 10:40:20 [Warning] [1985704653] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:8889->127.0.0.1:1056: wsasend: An established connection was aborted by the software in your host machine.
2021/10/12 10:40:21 127.0.0.1:1044 accepted //wsv3-widget.aicoin.net.cn:443 [DIRECT]
2021/10/12 10:40:21 127.0.0.1:1059 accepted //149.154.164.250:443 [ykqswftcowloggm]

**Comment by KukiSa** [comment]
@amiriliao Do not try to use a CDN (such as Cloudflare) to transfer connections that use XTLS.
