### ISSUE TITLE
能不能在执行脚本时知道当前xray的状态

### ISSUE THREAD

**Issue by mand-byte** [wulabing/Xray_onekey#378]
比如已安装，未运行
未安装，未运行
已安装，已运行

增加重启，停止菜单

**Comment by KukiSa** [comment]
@jonyhubber It is a proposal worth considering.

**Comment by suchacutesnake** [comment]
启动 Xray：`systemctl start xray`
停止 Xray：`systemctl stop xray`
查看Xray状态：`systemctl status xray`
可参考：[https://xtls.github.io/document/level-0/ch07-xray-server.html#_7-6-%E5%9B%9E%E9%A1%BE-systemd-%E8%BF%9B%E8%A1%8C%E5%9F%BA%E6%9C%AC%E7%9A%84%E6%9C%8D%E5%8A%A1%E7%AE%A1%E7%90%86](url)
