### ISSUE TITLE
SSL证书获取失败[BUG]

### ISSUE THREAD

**Issue by redcats2** [wulabing/Xray_onekey#383]
感谢你向 Xray_onekey 提交 issue！

在提交之前，请确认：

- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！
- [ ] 我已经在 [issues](https://github.com/wulabing/Xray_onekey/issues) 中找过我要提出的问题；
- [ ] 我已经使用最新版本的脚本测试过，问题依旧存在；
- [ ] 我已经仔细看过脚本报错提示并无法自行解决问题。

请注意，如果你没有遵照此 Issue Template 填写内容，我们将看心情关闭这个 issue。

------------------------------------------------------------------

### 服务运行情况

[Wed Dec 22 13:52:38 UTC 2021] Pending, The CA is processing your order, please just wait. (1/30)
[Wed Dec 22 13:52:41 UTC 2021] redcats4.f3322.net:Verify error:Fetching http://redcats4.f3322.net/.well-known/acme-challenge/REQ1G8-z8LLyxhnx1JFpPju3dyOxmbeQlWgIqO3Jb5A: Error getting validation data
[Wed Dec 22 13:52:41 UTC 2021] Please add '--debug' or '--log' to check more details.
[Wed Dec 22 13:52:41 UTC 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[ERROR]  SSL 证书生成失败 

### 环境 Environment

* 服务器提供商及服务器操作系统
……
* 是否全新安装
……
* 如果不是全新安装，有无安装其他软件（宝塔，Nginx等）
……
* 其他可以补充的信息
……

### 说明 Description

我使用的是公云的f3322免费DDNS服务，之前用一只是好的，最近更新vps重新配，遇到无法获取证书的问题，而且反复尝试多天，始终无法解决

在此处粘贴说明内容
```

### 重现问题的具体步骤

1. ...
2. ...
3. ...

**我预期会发生……？**
<!-- **Expected behavior:** [What you expected to happen] -->

**实际上发生了什么？**
<!-- **Actual behavior:** [What actually happened] -->

### 可能的解决方案 Possible Solution
<!-- 此项非必须，但是如果你有想法的话欢迎提出。 -->



### 更多信息 More Information

**Comment by KukiSa** [comment]
@redcats2 ``iptables -F``

**Comment by redcats2** [comment]
感谢！一语点醒梦中人
