### ISSUE TITLE
[BUG] SSL 证书生成失败 

### ISSUE THREAD

**Issue by xianvfx** [wulabing/Xray_onekey#385]
`
[Wed Jan 12 04:58:19 EST 2022] Installing cron job
43 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
[Wed Jan 12 04:58:19 EST 2022] Good, bash is found, so change the shebang to use bash as preferred.
[Wed Jan 12 04:58:20 EST 2022] OK
[Wed Jan 12 04:58:20 EST 2022] Install success!
[OK]  安装 SSL 证书生成脚本 完成 
[Wed Jan 12 04:58:22 EST 2022] Changed default CA to: https://acme-v02.api.letsencrypt.org/directory
[Wed Jan 12 04:58:22 EST 2022] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 60
[Wed Jan 12 04:58:22 EST 2022] Can not init api for: https://acme-v02.api.letsencrypt.org/directory.
......
[Wed Jan 12 05:00:03 EST 2022] Sleep 10 and retry.
[Wed Jan 12 05:00:14 EST 2022] Can not init api, for https://acme-v02.api.letsencrypt.org/directory
[ERROR]  SSL 证书生成失败 

`

**Comment by KukiSa** [comment]
@xianvfx ``yum install ca-certificates -y`` or ``apt install ca-certificates -y``
