### ISSUE TITLE
[BUG] 灵异bug

### ISSUE THREAD

**Issue by caixukundashabi** [wulabing/Xray_onekey#387]
我mac 使用v2rayU  经常上不了网  连接超时  然后我用ios的小飞机链接后随便访问个网站 可以打开后  mac才能上网
换了两台服务器都是这样 我想这是连接工具的问题 请问一下大家mac都是用什么连接工具

**Comment by KukiSa** [comment]
@caixukundashabi Your Issue does not conform to the template of this project. Your use of Issue to ask such questions may be difficult to obtain timely, effective, and scaled responses.
