### ISSUE TITLE
[BUG] SSL 证书生成失败 -Connection refused 查看了之前的Issue也无法解决

### ISSUE THREAD

**Issue by noucamp77** [wulabing/Xray_onekey#393]
感谢你向 Xray_onekey 提交 issue！

在提交之前，请确认：

- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！
- [X] 我已经在 [issues](https://github.com/wulabing/Xray_onekey/issues) 中找过我要提出的问题；
- [X] 我已经使用最新版本的脚本测试过，问题依旧存在；
- [X] 我已经仔细看过脚本报错提示并无法自行解决问题。

请注意，如果你没有遵照此 Issue Template 填写内容，我们将看心情关闭这个 issue。

------------------------------------------------------------------

### 服务运行情况

请运行命令 `service xray status` 并粘贴输出：

```
在此处粘贴输出内容
```
[root@newone ~]# service xray status
Redirecting to /bin/systemctl status xray.service
● xray.service - Xray Service
   Loaded: loaded (/etc/systemd/system/xray.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/xray.service.d
           └─10-donot_touch_single_conf.conf
   Active: active (running) since Fri 2022-02-25 09:51:14 UTC; 4min 45s ago
     Docs: https://github.com/xtls
 Main PID: 26881 (xray)
   CGroup: /system.slice/xray.service
           └─26881 /usr/local/bin/xray run -config /usr/local/etc/xray/config.json

Feb 25 09:51:14 newone systemd[1]: Started Xray Service.
Feb 25 09:51:14 newone xray[26881]: Xray 1.5.3 (Xray, Penetrates Everything.) Custom (go1.17.6 linux/amd64)
Feb 25 09:51:14 newone xray[26881]: A unified platform for anti-censorship.
Feb 25 09:51:14 newone xray[26881]: 2022/02/25 09:51:14 [Info] infra/conf/serial: Reading config: /usr/local/etc/xray/config.json
Feb 25 09:51:14 newone xray[26881]: 2022/02/25 09:51:14 [Warning] core: Xray 1.5.3 started

请运行命令 `service nginx status` 并粘贴输出：
```
在此处粘贴输出内容
```
service xray status
Redirecting to /bin/systemctl status xray.service
● xray.service - Xray Service
   Loaded: loaded (/etc/systemd/system/xray.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/xray.service.d
           └─10-donot_touch_single_conf.conf
   Active: active (running) since Fri 2022-02-25 09:51:14 UTC; 4min 45s ago
     Docs: https://github.com/xtls
 Main PID: 26881 (xray)
   CGroup: /system.slice/xray.service
           └─26881 /usr/local/bin/xray run -config /usr/local/etc/xray/config.json

Feb 25 09:51:14 newone systemd[1]: Started Xray Service.
Feb 25 09:51:14 newone xray[26881]: Xray 1.5.3 (Xray, Penetrates Everything.) Custom (go1.17.6 linux/amd64)
Feb 25 09:51:14 newone xray[26881]: A unified platform for anti-censorship.
Feb 25 09:51:14 newone xray[26881]: 2022/02/25 09:51:14 [Info] infra/conf/serial: Reading config: /usr/local/etc/xray/config.json
Feb 25 09:51:14 newone xray[26881]: 2022/02/25 09:51:14 [Warning] core: Xray 1.5.3 started
[root@newone ~]# service nginx status
Redirecting to /bin/systemctl status nginx.service
● nginx.service - nginx - high performance web server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2022-02-25 09:51:35 UTC; 5min ago
     Docs: http://nginx.org/en/docs/
  Process: 27879 ExecStop=/bin/sh -c /bin/kill -s TERM $(/bin/cat /var/run/nginx.pid) (code=exited, status=0/SUCCESS)
  Process: 27883 ExecStart=/usr/sbin/nginx -c /etc/nginx/nginx.conf (code=exited, status=0/SUCCESS)
 Main PID: 27884 (nginx)
   CGroup: /system.slice/nginx.service
           ├─27884 nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.conf
           └─27885 nginx: worker process

Feb 25 09:51:35 newone systemd[1]: Stopped nginx - high performance web server.
Feb 25 09:51:35 newone systemd[1]: Starting nginx - high performance web server...
Feb 25 09:51:35 newone nginx[27883]: nginx: [warn] conflicting server name "www.dfgdshh.ml" on 0.0.0.0:80, ignored
Feb 25 09:51:35 newone nginx[27883]: nginx: [warn] conflicting server name "www.dfgdshh.ml" on [::]:80, ignored
Feb 25 09:51:35 newone systemd[1]: Can't open PID file /var/run/nginx.pid (yet?) after start: No such file or directory
Feb 25 09:51:35 newone systemd[1]: Started nginx - high performance web server.

### 环境 Environment

* 服务器提供商及服务器操作系统
……
Centos 7.9
* 是否全新安装
……
是
* 如果不是全新安装，有无安装其他软件（宝塔，Nginx等）
……
* 其他可以补充的信息
……

### 说明 Description

```
在此处粘贴说明内容
```
使用下面的脚本安装xray,前面都顺利直到SSL证书生成失败。
wget -N --no-check-certificate -q -O install.sh "https://raw.githubusercontent.com/wulabing/Xray_onekey/main/install.sh" && chmod +x install.sh && bash install.sh

### 重现问题的具体步骤

1. ...
2. ...
3. ...

**我预期会发生……？**

**实际上发生了什么？**

[OK]  安装 SSL 证书生成脚本 完成
[Fri Feb 25 09:51:35 UTC 2022] Changed default CA to: https://acme-v02.api.letsencrypt.org/directory
[Fri Feb 25 09:51:36 UTC 2022] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Fri Feb 25 09:51:36 UTC 2022] Create account key ok.
[Fri Feb 25 09:51:36 UTC 2022] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Fri Feb 25 09:51:38 UTC 2022] Registered
[Fri Feb 25 09:51:38 UTC 2022] ACCOUNT_THUMBPRINT='nn5rhwOaT0OmL1vno90IO7FAFfUKL4XpLHmsVfsZkfc'
[Fri Feb 25 09:51:38 UTC 2022] Creating domain key
[Fri Feb 25 09:51:38 UTC 2022] The domain key is here: /root/.acme.sh/www.dfgdshh.ml_ecc/www.dfgdshh.ml.key
[Fri Feb 25 09:51:38 UTC 2022] Single domain='www.dfgdshh.ml'
[Fri Feb 25 09:51:38 UTC 2022] Getting domain auth token for each domain
[Fri Feb 25 09:51:41 UTC 2022] Getting webroot for domain='www.dfgdshh.ml'
[Fri Feb 25 09:51:41 UTC 2022] Verifying: www.dfgdshh.ml
[Fri Feb 25 09:51:42 UTC 2022] Pending, The CA is processing your order, please just wait. (1/30)
[Fri Feb 25 09:51:45 UTC 2022] www.dfgdshh.ml:Verify error:Fetching https://www.dfgdshh.ml/.well-known/acme-challenge/4uPVif0e6sBaVusMDVYRKP_sDeXSNxPWjEv-tQKAl-I: Connection refused
[Fri Feb 25 09:51:45 UTC 2022] Please add '--debug' or '--log' to check more details.
[Fri Feb 25 09:51:45 UTC 2022] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[ERROR]  SSL 证书生成失败

**Comment by KukiSa** [comment]
- After inquiries, I found out that you are using an Azure VM. Have you enabled the "Network Security Group" on the Azure Portal?
- CentOS is deprecated, it is recommended that you use Ubuntu or Debian.

**Comment by KukiSa** [comment]
@noucamp77 ``python3 -m http.server 80`` and try to access your IP address in browser.

**Comment by noucamp77** [comment]
Hi KukiSa,

I used another install script and it worked. Thanks a lot for your support!
