### ISSUE TITLE
怎么和V2board做对接？

### ISSUE THREAD

**Issue by wjsandy** [wulabing/Xray_onekey#395]
怎么和V2board做对接？
对接vmess+tcp+http
原生V2board不支持tcp+http订阅下发，请自行寻找解决方法，或手动配置客户端文件。
在对接vmess+tcp+http时，v2board需要在传输协议配置中增加如下内容：
{
  "header": {
    "type": "http",
    "request": {},
    "response": {}
  }
}
其中request和response中的内容请自行参照[Xray-core文档](https://xtls.github.io/config/transports/tcp.html#httpheaderobject)设置。

**Comment by KukiSa** [comment]
It is recommended to read the relevant documentation.

**Comment by imanenter** [comment]
> 怎么和V2board做对接？ 对接vmess+tcp+http 原生V2board不支持tcp+http订阅下发，请自行寻找解决方法，或手动配置客户端文件。 在对接vmess+tcp+http时，v2board需要在传输协议配置中增加如下内容： { "header": { "type": "http", "request": {}, "response": {} } } 其中request和response中的内容请自行参照[Xray-core文档](https://xtls.github.io/config/transports/tcp.html#httpheaderobject)设置。

hi, man did u find a way?
