### ISSUE TITLE
[BUG] ss_whitelist在ARM环境中docker compose无法正常加载工作

### ISSUE THREAD

**Issue by sora987** [wulabing/Xray_onekey#419]
root@debian:~# docker-compose -f /root/docker-compose.yml up
Creating network "root_backend" with driver "bridge"
Creating ipv6nat ... done
Creating root_shadowsocks_1 ... done
Creating root_openresty_1   ... done
Attaching to ipv6nat, root_shadowsocks_1, root_openresty_1
openresty_1    | exec /usr/bin/openresty: exec format error
shadowsocks_1  | INFO  shadowsocks server 1.15.0-alpha.5 build 2022-06-07T06:16:12.848150144+00:00
shadowsocks_1  | INFO  shadowsocks tcp server listening on 0.0.0.0:9866, inbound address 0.0.0.0:9866
shadowsocks_1  | INFO  shadowsocks udp server listening on 0.0.0.0:9866
root_openresty_1 exited with code 1
openresty_1    | exec /usr/bin/openresty: exec format error
openresty_1    | exec /usr/bin/openresty: exec format error
root_openresty_1 exited with code 1
openresty_1    | exec /usr/bin/openresty: exec format error
openresty_1    | exec /usr/bin/openresty: exec format error
openresty_1    | exec /usr/bin/openresty: exec format error
root_openresty_1 exited with code 1
openresty_1    | exec /usr/bin/openresty: exec format error
openresty_1    | exec /usr/bin/openresty: exec format error
openresty_1    | exec /usr/bin/openresty: exec format error
openresty_1    | exec /usr/bin/openresty: exec format error
root_openresty_1 exited with code 1
openresty_1    | exec /usr/bin/openresty: exec format error
openresty_1    | exec /usr/bin/openresty: exec format error
openresty_1    | exec /usr/bin/openresty: exec format error
openresty_1    | exec /usr/bin/openresty: exec format error
openresty_1    | exec /usr/bin/openresty: exec format error

......

无限循环，如果将image换成openresty/openresty:alpine-fat，那么openresty则不会报错，但是IP黑白名单无法正常工作，而是直接进入Welcome to OpenResty!页面...

测试环境是甲骨文的ARM小鸡，感谢大佬帮助！

**Comment by wulabing** [comment]
@sora987 这是因为openresty不同版本镜像的配置文件所在目录不同导致的 下个版本会将openresty的镜像切换到alpine版本来适配arm
