### ISSUE TITLE
[BUG][ERROR]  Nginx 启动 失败 

### ISSUE THREAD

**Issue by zyu** [wulabing/Xray_onekey#425]
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
[ERROR]  Nginx 启动 失败

**Comment by zyu** [comment]
ystemctl status nginx.service
● nginx.service - nginx - high performance web server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2022-10-03 10:27:41 EDT; 14s ago
     Docs: http://nginx.org/en/docs/
  Process: 3630 ExecStop=/bin/sh -c /bin/kill -s TERM $(/bin/cat /var/run/nginx.pid) (code=exited, status=0/SUCCESS)
  Process: 3641 ExecStart=/usr/sbin/nginx -c /etc/nginx/nginx.conf (code=exited, status=1/FAILURE)
 Main PID: 3604 (code=exited, status=0/SUCCESS)

Oct 03 10:27:41 racknerd-42fa39 systemd[1]: Starting nginx - high performance web server...
Oct 03 10:27:41 racknerd-42fa39 nginx[3641]: nginx: [emerg] SSL_CTX_set1_curves_list("X25519:P-256:P-384:P-521") failed
Oct 03 10:27:41 racknerd-42fa39 systemd[1]: nginx.service: control process exited, code=exited status=1
Oct 03 10:27:41 racknerd-42fa39 systemd[1]: Failed to start nginx - high performance web server.
Oct 03 10:27:41 racknerd-42fa39 systemd[1]: Unit nginx.service entered failed state.
Oct 03 10:27:41 racknerd-42fa39 systemd[1]: nginx.service failed.

**Comment by zywj** [comment]
同错误，  centos 7

**Comment by weilingwei** [comment]
同错误， centos 7

**Comment by KukiSa** [comment]
@weilingwei @zywj @zyu Debian 11 please.

**Comment by myy520** [comment]
同错cenos7

**Comment by KukiSa** [comment]
@myy520 https://github.com/wulabing/Xray_onekey/issues/425#issuecomment-1266432035

**Comment by hadow** [comment]
same error

**Comment by hadow** [comment]
same error centos 7

**Comment by KukiSa** [comment]
@hadow Debian 10+ / Ubuntu 20.04+, plz.

**Comment by Donotinvert** [comment]
same error

**Comment by JimyuAn-98** [comment]
同错误，centos 7

**Comment by derek0x** [comment]
same error centos 7

**Comment by crazymartin** [comment]
用centos8 就不报错了

**Comment by jiuqi9997** [comment]
更换debian解决。

**Comment by Deepsea-CN** [comment]
SSL_CTX_set1_curves_list("X25519:P-256:P-384:P-521") failed
把x25519加密删掉就好，在配置文件里
