### ISSUE TITLE
（Xray 前置）伪装域名的网址打不开

### ISSUE THREAD

**Issue by Yuri2** [wulabing/Xray_onekey#427]
感谢你向 Xray_onekey 提交 issue！
（Xray 前置）伪装域名的网址打不开
提示：

请试试以下办法：

检查网络连接
[检查代理服务器和防火墙](chrome-error://chromewebdata/#buttons)
[运行 Windows 网络诊断](javascript:diagnoseErrors())
ERR_CONNECTION_CLOSED

在提交之前，请确认：

- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！
- [ ] 我已经在 [issues](https://github.com/wulabing/Xray_onekey/issues) 中找过我要提出的问题；
- [ ] 我已经使用最新版本的脚本测试过，问题依旧存在；
- [ ] 我已经仔细看过脚本报错提示并无法自行解决问题。

请注意，如果你没有遵照此 Issue Template 填写内容，我们将看心情关闭这个 issue。

------------------------------------------------------------------

### 服务运行情况

请运行命令 `service xray status` 并粘贴输出：

```
在此处粘贴输出内容
```
请运行命令 `service nginx status` 并粘贴输出：
```
在此处粘贴输出内容
```（Xray 前置）伪装域名的网址打不开



### 环境 Environment

* 服务器提供商及服务器操作系统
……
* 是否全新安装
……
* 如果不是全新安装，有无安装其他软件（宝塔，Nginx等）
……
* 其他可以补充的信息
……

### 说明 Description

<!--
请详细、清晰地表达你要提出的论述，例如这个问题如何影响到你？你想实现什么功能？
-->
```
在此处粘贴说明内容
```

### 重现问题的具体步骤

1. ...
2. ...
3. ...

**我预期会发生……？**
<!-- **Expected behavior:** [What you expected to happen] -->

**实际上发生了什么？**
<!-- **Actual behavior:** [What actually happened] -->

### 可能的解决方案 Possible Solution
<!-- 此项非必须，但是如果你有想法的话欢迎提出。 -->



### 更多信息 More Information

**Comment by PixelMonkeyPro** [comment]
我以前是通过修改Nginx配置文件来搞定的

**Comment by newman-shark** [comment]
> 我以前是通过修改Nginx配置文件来搞定的

你好，请教一下，是咋修改的呢
