### ISSUE TITLE
证书一直生成失败  怎么解决？

### ISSUE THREAD

**Issue by Weikn** [wulabing/Xray_onekey#428]
[OK]  安装 SSL 证书生成脚本 完成
[Sun Oct  9 13:32:02 UTC 2022] Changed default CA to: https://acme-v02.api.letsencrypt.org/directory
[Sun Oct  9 13:32:03 UTC 2022] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sun Oct  9 13:32:03 UTC 2022] Create account key ok.
[Sun Oct  9 13:32:03 UTC 2022] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Sun Oct  9 13:32:04 UTC 2022] Registered
[Sun Oct  9 13:32:04 UTC 2022] ACCOUNT_THUMBPRINT='mMOpiMi6T_WO6vJFLS-ivbId2a5tws3zI-BJc03lj3g'
[Sun Oct  9 13:32:04 UTC 2022] Creating domain key
[Sun Oct  9 13:32:04 UTC 2022] The domain key is here: /root/.acme.sh/www.aweikn.cn_ecc/www.aweikn.cn.key
[Sun Oct  9 13:32:04 UTC 2022] Single domain='www.aweikn.cn'
[Sun Oct  9 13:32:04 UTC 2022] Getting domain auth token for each domain
[Sun Oct  9 13:32:04 UTC 2022] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: www.aweikn.cn, retry after 2022-10-10T11:54:14Z: see https://letsencrypt.org/docs/duplicate-certificate-limit/",
  "status": 429
}
[Sun Oct  9 13:32:04 UTC 2022] Please add '--debug' or '--log' to check more details.
[Sun Oct  9 13:32:04 UTC 2022] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Sun Oct  9 13:32:04 UTC 2022] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sun Oct  9 13:32:04 UTC 2022] Single domain='www.aweikn.cn'
[Sun Oct  9 13:32:04 UTC 2022] Getting domain auth token for each domain
[Sun Oct  9 13:32:05 UTC 2022] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: www.aweikn.cn, retry after 2022-10-10T11:54:14Z: see https://letsencrypt.org/docs/duplicate-certificate-limit/",
  "status": 429
}
[Sun Oct  9 13:32:05 UTC 2022] Please add '--debug' or '--log' to check more details.
[Sun Oct  9 13:32:05 UTC 2022] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[ERROR]  SSL 证书生成失败

**Comment by skllskll** [comment]
同样的问题？证书过期了

**Comment by amsz** [comment]
修改 install.sh 脚本: `githubusercontents.com`  -> `githubusercontent.com`

**Comment by dong50252409** [comment]
我也遇到同样的问题了，按照@amsz 的示例替换后仍未解决

**Comment by shijia7** [comment]
too many certificates (5) already issued for this exact set of domains in the last 168 hours。

一周后再试

**Comment by abel533** [comment]
是否修改过端口，然后失败的？如果是，临时的办法是改回去，更新证书，再改回去。

**Comment by ufoozhenghao** [comment]
证书一直生成失败 是否可以添加手工导入选项？

**Comment by jiuqi9997** [comment]
申请的证书太多了，等。
