### ISSUE TITLE
[BUG] 修改端口后，更新证书仍然访问的旧端口，导致更新失败

### ISSUE THREAD

**Issue by abel533** [wulabing/Xray_onekey#433]
感谢你向 Xray_onekey 提交 issue！

在提交之前，请确认：

- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！
- [x] 我已经在 [issues](https://github.com/wulabing/Xray_onekey/issues) 中找过我要提出的问题；
- [x] 我已经使用最新版本的脚本测试过，问题依旧存在；
- [ ] 我已经仔细看过脚本报错提示并无法自行解决问题。

请注意，如果你没有遵照此 Issue Template 填写内容，我们将看心情关闭这个 issue。

------------------------------------------------------------------

比如一开始使用 443端口，更新证书正常。

443端口被封后，通过脚本修改端口为12345，使用正常，但是更新证书仍然使用443端口访问，导致更新失败。

**Comment by huluohu** [comment]
> 感谢你向 Xray_onekey 提交 issue！
> 
> 在提交之前，请确认：
> 
> * [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧！
> * [x]  我已经在 [issues](https://github.com/wulabing/Xray_onekey/issues) 中找过我要提出的问题；
> * [x]  我已经使用最新版本的脚本测试过，问题依旧存在；
> * [ ]  我已经仔细看过脚本报错提示并无法自行解决问题。
> 
> 请注意，如果你没有遵照此 Issue Template 填写内容，我们将看心情关闭这个 issue。
> 
> 比如一开始使用 443端口，更新证书正常。
> 
> 443端口被封后，通过脚本修改端口为12345，使用正常，但是更新证书仍然使用443端口访问，导致更新失败。

先把端口改为443，再更新证书，然后再把端口改回去。

**Comment by abel533** [comment]
@huluohu 之前就是这么解决的...自动更新方式不行了。

**Comment by aaronchin** [comment]
手动把nginx加上443port设定
