### ISSUE TITLE
How I can add new users?

### ISSUE THREAD

**Issue by amirreza225** [wulabing/Xray_onekey#434]
Thank for your excellent script 
How I can add new users? is there any panel for that ? how can I access it?

**Comment by abelyuan00** [comment]
You can simply add a new user in the config.json file, it will look like this: 
`{ "log": { "access": "/var/log/xray/access.log", "error": "/var/log/xray/error.log", "loglevel": "warning" }, "stats": {}, "api": { "tag": "api", "services": [ "StatsService" ] }, "policy": { "levels": { "0": { "statsUserUplink": true, "statsUserDownlink": true } }, "system": { "statsInboundUplink": true, "statsInboundDownlink": true, "statsOutboundUplink": true, "statsOutboundDownlink": true } }, "inbounds": [ { "port": 24661, "protocol": "vless", "settings": { "clients": [ { "email": "user-1st", "id": "a8ea8150-4f17-4d44-a92a-0dcb843f615f", "flow": "xtls-rprx-direct" }, { "email": "user-hEFFj1PURP", "id": "d25d6c39-0110-4454-a5e0-9070862860de", "flow": "xtls-rprx-direct" } ], "decryption": "none", "fallbacks": [ { "dest": 60000, "alpn": "", "xver": 1 }, { "dest": 60001, "alpn": "h2", "xver": 1 } ] }, "streamSettings": { "network": "tcp", "security": "xtls", "xtlsSettings": { "minVersion": "1.2", "certificates": [ { "certificateFile": "/usr/local/etc/xray/self_signed_cert.pem", "keyFile": "/usr/local/etc/xray/self_signed_key.pem" }, { "certificateFile": "/ssl/xray.crt", "keyFile": "/ssl/xray.key" } ] } }, "sniffing": { "enabled": true, "destOverride": [ "http", "tls" ] } }, { "listen": "127.0.0.1", "port": 24661, "protocol": "dokodemo-door", "settings": { "address": "127.0.0.1" }, "tag": "api" } ], "outbounds": [ { "protocol": "freedom" } ], "routing": { "rules": [ { "inboundTag": [ "api" ], "outboundTag": "api", "type": "field" } ], "domainStrategy": "AsIs" } }
`

**Comment by abelyuan00** [comment]
you can simply change the config.json file directly, it might look like this:
`{
    "log": {
        "access": "/var/log/xray/access.log",
        "error": "/var/log/xray/error.log",
        "loglevel": "warning"
    },
    "stats": {},
    "api": {
        "tag": "api",
        "services": [
            "StatsService"
        ]
    },
    "policy": {
        "levels": {
            "0": {
                "statsUserUplink": true,
                "statsUserDownlink": true
            }
        },
        "system": {
            "statsInboundUplink": true,
            "statsInboundDownlink": true,
            "statsOutboundUplink": true,
            "statsOutboundDownlink": true
        }
    },
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "email": "user-1st",
                        "id": "",
                        "flow": "xtls-rprx-direct"
                    },
                    {
                        "email": "user-2nd",
                        "id": "",
                        "flow": "xtls-rprx-direct"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 60000,
                        "alpn": "",
                        "xver": 1
                    },
                    {
                        "dest": 60001,
                        "alpn": "h2",
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "minVersion": "1.2",
                    "certificates": [
                        {
                            "certificateFile": "/usr/local/etc/xray/self_signed_cert.pem",
                            "keyFile": "/usr/local/etc/xray/self_signed_key.pem"
                        },
                        {
                            "certificateFile": "/ssl/xray.crt",
                            "keyFile": "/ssl/xray.key"
                        }
                    ]
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
        },
        {
            "listen": "127.0.0.1",
            "port": 24661,
            "protocol": "dokodemo-door",
            "settings": {
                "address": "127.0.0.1"
            },
            "tag": "api"
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ],
    "routing": {
        "rules": [
            {
                "inboundTag": [
                    "api"
                ],
                "outboundTag": "api",
                "type": "field"
            }
        ],
        "domainStrategy": "AsIs"
    }
}`
