### ISSUE TITLE
用NGINX前置版本一键安装后，客户端提示io read/write on closed pipe

### ISSUE THREAD

**Issue by mayaren888** [wulabing/Xray_onekey#435]
第一次使用您的一键安装版本，不知道问题出在哪里。
我是用的是ubuntu 20.04 LTS 服务器版本
用的NGINX前置版本，选择安装后客户端添加节点
客户端运行测试始终显示io read/write on closed pipe，时钟这块肯定是没问题的。

**Comment by Changego** [comment]
同问+1

**Comment by Mr-Cyber-Security** [comment]
同问+1

**Comment by Mr-Cyber-Security** [comment]
> 

### 我的问题解决了
1. 同步服务器时区
2. 查看客户端配置，url导入是有点问题的
