### ISSUE TITLE
为什么我域名正确，它一直获取不到。

### ISSUE THREAD

**Issue by DMC-cmd997** [wulabing/Xray_onekey#436]
请输入你的域名信息(eg: www.wulabing.com):我的域名
[OK]  正在获取 IP 地址信息，请耐心等待 
域名通过 DNS 解析的 IP 地址：我的域名
本机公网 IPv4 地址： 
本机公网 IPv6 地址： 
[ERROR]  请确保域名添加了正确的 A / AAAA 记录，否则将无法正常使用 xray 
[ERROR]  域名通过 DNS 解析的 IP 地址与 本机 IPv4 / IPv6 地址不匹配，是否继续安装？（y/n） 

![1](https://user-images.githubusercontent.com/80573027/206431776-ba44f37c-ce68-482d-a970-c16fc7407297.jpg)

**Comment by sd19836311** [comment]
问到了同样的问题。已经切换域名商也没用

**Comment by xooxoodark** [comment]
https://github.com/wulabing/Xray_onekey/blob/d296c8130bfb342c6ec6fc587d16381f8897513a/install.sh#L245 
https://github.com/wulabing/Xray_onekey/blob/d296c8130bfb342c6ec6fc587d16381f8897513a/install.sh#L246 

换成
local_ipv4=$(curl -s4m8 https://ifconfig.co/)
local_ipv6=$(curl -s6m8 https://ifconfig.co/)

试试

**Comment by DMC-cmd997** [comment]
> https://github.com/wulabing/Xray_onekey/blob/d296c8130bfb342c6ec6fc587d16381f8897513a/install.sh#L245
> 
> 
> https://github.com/wulabing/Xray_onekey/blob/d296c8130bfb342c6ec6fc587d16381f8897513a/install.sh#L246
> 
> 换成 local_ipv4=$(curl -s4m8 https://ifconfig.co/) local_ipv6=$(curl -s6m8 https://ifconfig.co/)
> 
> 试试

可以了，谢谢。

**Comment by coldsaber** [comment]
我在更新之后也无法获得主机地址，代码显示如下：（中间html部分是直接显示出来的）
没想明白这个403 forbidden是怎么来的……

请输入你的域名信息(eg: www.wulabing.com): 我的域名
[OK]  正在获取 IP 地址信息，请耐心等待 
域名通过 DNS 解析的 IP 地址：我的主机地址
本机公网 IPv4 地址： <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
本机公网 IPv6 地址： 
[ERROR]  请确保域名添加了正确的 A / AAAA 记录，否则将无法正常使用 xray 
[ERROR]  域名通过 DNS 解析的 IP 地址与 本机 IPv4 / IPv6 地址不匹配，是否继续安装？（y/n）

**Comment by xooxoodark** [comment]
源出问题了，我这里找个新的。。。

**Comment by xooxoodark** [comment]
可以试试这个 https://github.com/xooxoodark/Xray_onekey/tree/patch-1

**Comment by Rangtian** [comment]
> https://github.com/wulabing/Xray_onekey/blob/d296c8130bfb342c6ec6fc587d16381f8897513a/install.sh#L245
> 
> https://github.com/wulabing/Xray_onekey/blob/d296c8130bfb342c6ec6fc587d16381f8897513a/install.sh#L246
> 
> 换成 local_ipv4=$(curl -s4m8 https://ifconfig.co/) local_ipv6=$(curl -s6m8 https://ifconfig.co/)
> 
> 试试

感谢大佬！

**Comment by asdffgdsf** [comment]
> https://github.com/wulabing/Xray_onekey/blob/d296c8130bfb342c6ec6fc587d16381f8897513a/install.sh#L245
> 
> 
> https://github.com/wulabing/Xray_onekey/blob/d296c8130bfb342c6ec6fc587d16381f8897513a/install.sh#L246
> 
> 换成 local_ipv4=$(curl -s4m8 https://ifconfig.co/) local_ipv6=$(curl -s6m8 https://ifconfig.co/)
> 
> 试试

大佬，这个怎么换啊

**Comment by tiancaicai1** [comment]
这个怎替换的

**Comment by tiancaicai1** [comment]
我小白来的，有视频啥的或者联系方式的，可以学习一下的额

**Comment by Rangtian** [comment]
半年过去了，这BUG还没修。
请问脚本停止维护了么？
