### ISSUE TITLE
[Warning] 该脚本部署的服务器存在严重的TLS指纹泄露问题，大部分用户出现相同的指纹

### ISSUE THREAD

**Issue by Billyas** [wulabing/Xray_onekey#444]
该脚本会自动写入特定的Nginx 配置文件，该配置文件中指定SSL加密版本等重要信息，经过校验，某些参数可能导致出现固定的TLS指纹。通过 [jarm](https://github.com/salesforce/jarm) 可以获取某一域名的tls指纹hash信息。

通过 [FOFA](https://fofa.info) 查询相关的指纹hash值可以发现存在大量相同指纹的服务器，均是采用本脚本部署。以下是搜索参数
```
jarm="00000000000000000042d43d0000009535d5979f591ae8e547c5e5743e5b64" && region="HK" && "3D元素周期表"
```

![image](https://user-images.githubusercontent.com/62041096/218121250-30a7f0da-0f4c-4acc-bd81-e96671b9c3b7.png)

解决方法，修改脚本中写死的 SSL相关参数，即可改变tls指纹。

**Comment by chrisqin** [comment]
其实最大问题应该是3D元素周期表吧

**Comment by Billyas** [comment]
> 其实最大问题应该是3D元素周期表吧

其实3d元素周期表只是一个最明显的特征，去除这个搜索信息依然会发现大量相同特征的服务器，这些特征是由相同的NGINX 配置文件ssl参数产生的

**Comment by AllenMeex** [comment]
请问“修改脚本中写死的 SSL相关参数，即可改变tls指纹”具体是指哪段代码

**Comment by Billyas** [comment]
> 请问“修改脚本中写死的 SSL相关参数，即可改变tls指纹”具体是指哪段代码

https://github.com/wulabing/Xray_onekey/blob/32b7042694912aee3e51b58eff9b0499046b1f26/install.sh#L561
