### ISSUE TITLE
Deprecate xtls-rprx-direct

### ISSUE THREAD

**Issue by EdiWang** [wulabing/Xray_onekey#445]
`xtls-rprx-direct` is marked deprecated on https://xtls.github.io/config/outbounds/vless.html#userobject

This script is using `xtls-rprx-direct`, which produce a warning on latest version (1.7.5) of xray:

```
2023/02/16 19:00:34 [Warning] infra/conf: You are using an old version of XTLS, which is deprecated now and will be removed soon. Please use flow "xtls-rprx-vision" with "tls & tlsSettings" instead.
```

Please consider migrate to `xtls-rprx-vision`

Thanks

**Comment by mcmoodoo** [comment]
Perfect! I was just running into the issue of not being able to start the xray server. Thanks!
