### ISSUE TITLE
怎么更换UUID

### ISSUE THREAD

**Issue by zavierwo** [wulabing/Xray_onekey#446]

**Comment by abelyuan00** [comment]
配置文件修改即可，config.json文件中，记得在代理中也要更换相应uuid

**Comment by EdiWang** [comment]
Execute `sudo bash install.sh` again, and select option 11.

![image](https://user-images.githubusercontent.com/3304703/220254772-0af83afe-6678-4d22-b591-9fbdc2bd5f16.png)
