### ISSUE TITLE
 SSL 证书生成失败 

### ISSUE THREAD

**Issue by hotzwd** [wulabing/Xray_onekey#447]
感谢你向 Xray_onekey 提交 issue！

在提交之前，请确认：

- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！
- [ ] 我已经在 [issues](https://github.com/wulabing/Xray_onekey/issues) 中找过我要提出的问题；
- [ ] 我已经使用最新版本的脚本测试过，问题依旧存在；
- [ ] 我已经仔细看过脚本报错提示并无法自行解决问题。

请注意，如果你没有遵照此 Issue Template 填写内容，我们将看心情关闭这个 issue。

------------------------------------------------------------------

### 服务运行情况

Redirecting to /bin/systemctl status xray.service
● xray.service - Xray Service
   Loaded: loaded (/etc/systemd/system/xray.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/xray.service.d
           └─10-donot_touch_single_conf.conf
   Active: active (running) since Wed 2023-02-22 03:39:06 UTC; 3min 33s ago
     Docs: https://github.com/xtls
 Main PID: 5193 (xray)
   CGroup: /system.slice/xray.service
           └─5193 /usr/local/bin/xray run -config /usr/local/etc/xray/config.json

```
在此处粘贴输出内容
```
请运行命令 `service nginx status` 并粘贴输出：
```
在此处粘贴输出内容
```

### 环境 Environment

* 服务器提供商及服务器操作系统
……
* 是否全新安装
……
* 如果不是全新安装，有无安装其他软件（宝塔，Nginx等）
……
* 其他可以补充的信息
……

### 说明 Description

```
在此处粘贴说明内容
```

### 重现问题的具体步骤

1. ...
2. ...
3. ...

**我预期会发生……？**

**实际上发生了什么？**

**Comment by fieri** [comment]
碰到同样问题，CENTOS 7

**Comment by snowroll** [comment]
> 
换ubuntu，亲测可行

**Comment by ruanimal** [comment]
把 iptables 规则清一下

**Comment by szz1233** [comment]
> 把 iptables 规则清一下

请问大佬具体怎样做

**Comment by aJIEw** [comment]
`iptables -F` 不一定有用，我尝试了下发现原因是 nginx 不能正常启动。因此，假如你不是在全新的 vps 上第一次使用该脚本，可以先看下 nginx 是否启动报错了。

我的话是因为之前已经运行过脚本并且安装了 nginx，再次启动脚本的时候 nginx 使用了旧的证书路径，导致无法正常启动 (cannot load certificate)，解决了这个问题之后再运行脚本就可以正常生成证书了。

如果还是不行，最好先检查下你的域名能否正常访问：
```sh
curl -IkL -m20 http://[your domain]
```
