### ISSUE TITLE
现在只要稍微大流量就会被封端口，这个能解决吗？

### ISSUE THREAD

**Issue by Alyle-L** [wulabing/Xray_onekey#448]
现在只要稍微大流量就会被封端口，这个能解决吗？

**Comment by zyc86552834** [comment]
最近我也遇到这个问题了，看个youtube马上就会被封端口，只能换个端口接着用。。。

**Comment by zyc86552834** [comment]
> 现在只要少量大流量就会被封端口，这个能解决吗？

可以尝试加CDN，我尝试两天，目前还比较稳定

**Comment by Alyle-L** [comment]
加了cdn后比较玄学，总体还可用，晚高峰就........

**Comment by Alyle-L** [comment]
加了cdn后整体体验差了一些，不过这个是垃圾vps的神器，哈哈

**Comment by sistinafibe** [comment]
同样 不知道是不是因为这两天开会的原因

**Comment by EdiWang** [comment]
不止这个脚本的配置方式。VMESS+WS+TLS / VLESS+WS+TLS 也一样现象。

**Comment by wantflyfly** [comment]
端口为什么这么容易被封啊

**Comment by 3339588491** [comment]
除了添加cdn还有什么方法可以解决端口被封的问题吗？
