### ISSUE TITLE
希望一键脚本可以自动校准时区

### ISSUE THREAD

**Issue by karllao** [wulabing/Xray_onekey#449]
今天安装了VLESS + TCP + TLS + Nginx + WebSocket，折腾了一个小时一直连接不上，把时区校准回来Asia/Shanghai之后就正常了

**Comment by Grey0520** [comment]
同意！
我的云厂商不会自动配置时区，之前也遇到问题，后来才琢磨明白的

**Comment by jiuqi9997** [comment]
协议对时间同步的要求与时区无关。另外VLESS不要求时间同步。TLS有一定要求，不过也与时区无关。
