### ISSUE TITLE
[BUG] install.sh: line 123: [[: 20.04: syntax error: invalid arithmetic operator (error token is ".04")

### ISSUE THREAD

**Issue by jiangying000** [wulabing/Xray_onekey#451]
wget -N --no-check-certificate -q -O install.sh "https://raw.githubusercontent.com/wulabing/Xray_onekey/nginx_forward/install.sh" && chmod +x install.sh && bash install.sh

在 ubuntu 20.04 报：

install.sh: line 123: [[: 20.04: syntax error: invalid arithmetic operator (error token is ".04")

**Comment by aJIEw** [comment]
字符串比较的问题，把 [123 行](https://github.com/wulabing/Xray_onekey/blob/f506f1d48a70d042c275dcfbd1476779dde6d708/install.sh#L123)的
```sh
if [[ ${VERSION_ID} -ge 20 ]]; then
```
改成：
```sh
if [[ $(echo "${VERSION_ID}" | cut -d '.' -f1) -ge 20 ]]; then
```
参考：[Bash Script to set Linux OS](https://serverfault.com/questions/686606/bash-script-to-set-linux-os)
