### ISSUE TITLE
请教一个比较弱智的问题

### ISSUE THREAD

**Issue by ilivid** [wulabing/Xray_onekey#453]
已经成功安装： VLESS+TCP+TLS+Nginx with WebSocket 混合模式 安装成功 。但是请问之后应该怎么用....？

**Comment by ilivid** [comment]
一直显示超时

**Comment by wuhuihong** [comment]
> 已经成功安装： VLESS+TCP+TLS+Nginx with WebSocket 混合模式 安装成功 。但是请问之后应该怎么用....？

windows客户端用V2rayN，iOS用shadowrocket，把链接直接粘贴到客户端就行了

**Comment by TremblingFool** [comment]
建议你还是百度下VPS的搭建教程吧，那个介绍的详细
