### ISSUE TITLE
端口基本一天封一次，怎么破

### ISSUE THREAD

**Issue by weijianghu** [wulabing/Xray_onekey#457]
端口基本一天封一次，怎么破

**Comment by 3339588491** [comment]
同问＋1

**Comment by wulabing** [comment]
建议使用 naiveproxy 或者使用 xray reality 新协议

**Comment by 3339588491** [comment]
> 建议使用 naiveproxy 或者使用 xray reality 新协议

方面讲一下具体怎么操作吗？

**Comment by caohanwu** [comment]
wget -P /root -N --no-check-certificate "https://raw.githubusercontent.com/mack-a/v2ray-agent/master/install.sh" && chmod 700 /root/install.sh && /root/install.sh

**Comment by jieran233** [comment]
> > 建议使用 naiveproxy 或者使用 xray reality 新协议
> 
> 方面讲一下具体怎么操作吗？

https://github.com/mack-a/v2ray-agent/
https://www.v2ray-agent.com/archives/1680104902581

**Comment by haov000** [comment]
端口一天一封，更换了楼上xray reality，上网速度没问题，但是浏览youtube明显速度不如这个，不知道为什么
