### ISSUE TITLE
是不是被恶意注入了

### ISSUE THREAD

**Issue by iiiLFC** [wulabing/Xray_onekey#460]
VPS运营商给我邮件：检测到您的域名或您的网络中的一台机器试图通过SSH/FTP暴力破解账户密码。附上攻击的主机和活动的时间/日期。请采取必要的措施，立即停止这种活动。如果您有任何问题，请回复此邮件。

用了几年很好，但是最近在新VPS上收到这个报告，OS也没有安装别的脚本。

具体是我的IP试图破解一个德国的IP

**Comment by jiuqi9997** [comment]
这是你的VPS被人入侵了，跟脚本无关，自己问题
